scieloorg/packtools

- HISTORY.md
- README.md
- packtools/stylechecker.py
- packtools/version.py
The basic output is now presented as JSON structure. The option
*--assetsdir* lookups, in the given dir, for each asset referenced in
XML. The *--annotated* option now writes the output to a file. The
utility now takes more than one XML a time.
> Stylechecker utility output overhaul.

- packtools/catalogs/__init__.py
- packtools/catalogs/default-html.xslt
- packtools/catalogs/htmlgenerator/root-html-1.2.xslt
- packtools/domain.py
- packtools/htmlgenerator.py
- tests/test_htmlgenerator.py
Criar um novo template para gerar HTML para a pre-visualização do XML.
```
htmlgenerator PATH_XML [--nochecks] [--css=PATH_CSS]
```
Deve gerar um arquivo HTML para cada idioma no XML.
> nova versão do HTML gerado, e com suporte para CSS

- HISTORY.rst
- packtools/stylechecker.py
Now the summary and annotation features can be used by calling
``stylechecker.summarize`` and ``stylechecker.annotate`` functions.
> Makes stylechecker more reusable.

- .travis.yml
- HISTORY.rst
- packtools/domain.py
- packtools/stylechecker.py
- packtools/utils.py
- setup.py
- tests/test_utils.py
- tox.ini
The new function ``stylechecker.validate_zip_package`` can perform full validations on zip packages, including assets lookup.
The method ``XMLValidation.lookup_assets`` now receives any object that supports the ``in`` operator.
> Adds zip-file validation capabilities.

- HISTORY.rst
- packtools/catalogs/__init__.py
- packtools/stylechecker.py
- packtools/utils.py
- tests/test_utils.py
Make built-in schematron schemas available through the prefix `@`:
@scielo-br, @sps-1.1, @sps-1.2, @sps-1.3, @sps-1.4, @sps-1.5.
> Make built-in schematron schemas available via stylechecker.

- setup.cfg
- setup.py
Binary wheels built using setuptools < 18 do not support the syntax for conditional dependencies based on the `extras_require` param, e.g.: `dict(':python_version<"3.4"'=['pathlib>=1.0.1'])`.
> Fixes bdist_wheel builds.

- packtools/catalogs/htmlgenerator/v2.0/article-text-formula.xsl
Este pull request  modifica a XLS das `disp-formula` com match em `tex-math` e:
- Encapsula os `labels` em uma tag HTML com um identificador para posterior tratamento via CSS
- Remove o preâmbulo de fórmulas matemáticas do tipo LaTeX e assim prover a compatibilidade com o site antigo.
Este PR pode ser revisado a partir do arquivo:
- `packtools/catalogs/htmlgenerator/v2.0/article-text-formula.xsl`
- Rodando os testes com `python setup.py test`
- ```htmlgenerator 1980-5381-neco-28-02-385.xml```  - [XML](https://new.scielo.br/article/ssm/content/raw/\?resource_ssm_path\=/media/assets/neco/v28n2/1980-5381-neco-28-02-385.xml)
N/A
N/A
#168
#169
N/A
> Modifica a XSL para comportar funcionalidades legadas do site vintage

- packtools/catalogs/htmlgenerator/v2.0/config-labels.xml
- packtools/catalogs/htmlgenerator/v2.0/generic-pub-date.xsl
Esse PR Ajustar os termos utilizados no bloco de visualização para as datas de publicação como descrito no ticket scieloorg/opac#1180 e incorporado pelo PR #194 
Pelos arquivos
* `packtools/catalogs/htmlgenerator/v2.0/config-labels.xml`
* `packtools/catalogs/htmlgenerator/v2.0/generic-pub-date.xsl`
Apos atualizar o pacote e gerar o html de um xml, verifique se o html produzido condiz com o esperado
scieloorg/opac#1180
> Ajustes no label das traduções scieloorg/opac#1180

- packtools/catalogs/htmlgenerator/v2.0/article-meta-contrib.xsl
Esse PR corrige a duplicação da div `contribGroup` assim evitando a duplicação de autores na visualização do artigo 
Pelo arquivo 
* `packtools/catalogs/htmlgenerator/v2.0/article-meta-contrib.xsl`
Apos atualizar o packtools e o ambinete local do opac, tente acessar alguns artigos e em especial o 
`http://0.0.0.0:5000/article/abc/2018.v111n3/436-539/` que ocasionou todo o problema
Quando o Artigo possui mais de 10 autores aparece um collapse `[...]` que em alguns casos estava seno duplicado
N/A
scieloorg/opac#1311
https://github.com/scieloorg/opac/issues/1311#issuecomment-508259339
> Correção para não ocorrer duplicação da div 'contribGroup'

- packtools/catalogs/htmlgenerator/v2.0/article-text-fig.xsl
- tests/test_htmlgenerator.py
Adiciona a capacidade de obter imagens e caption de visual abstract.
Nos módulos: 
```python
packtools/catalogs/htmlgenerator/v2.0/article-text-fig.xsl
tests/test_htmlgenerator.py
```
Executando o comando: 
```python
python setup.py test
```
Não há.
https://github.com/scieloorg/opac/issues/1363
Não há .
Como foi resolvido essa demanda:
No XML a tag que representa o "Visual Abstract" é a tag abstract com um atributo abstract-type="graphical", exemplo:
```xml
<abstract abstract-type="graphical">
<title>qualquer coisa</title>
<p>
<fig id="vf01">
<caption>
<title>Texto em inglês<italic>propensity-score
matching</italic></title>
</caption>
<graphic xlink:href="2175-8239-jbn-2018-0058-vf01.jpg"/>
</fig>
</p>
</abstract>
```
Na XSL adicionamos as seguintes linhas de código:
```xml
<xsl:template …
```
> Adiciona suporte para visual abstract na página do artigo

- packtools/catalogs/htmlgenerator/v2.0/generic-history.xsl
- tests/samples/0034-7094-rba-69-03-0227.xml
- tests/test_htmlgenerator.py
Este pull request corrige os apontamentos do ticket https://github.com/scieloorg/opac/issues/1393. Foi alterado o modo escolhido para aplicar a marcação dos itens capturados durante o *parser* do histórico.
- `packtools/catalogs/htmlgenerator/v2.0/generic-history.xsl` L `55`
Para testar este pull request manualmente deve-se:
- Faça o download do [XML](https://github.com/scieloorg/opac/files/3473960/0034-7094-rba-69-03-0227.txt);
- Execute o `htmlgenerator`;
- Abra o artigo na versão `en`;
- Abra o artigo na versão `pt`;
- Verifique que para os dois idiomas os marcadores de datas são exibidos;
N/A
*Anteriormente o HTML era gerado desta forma*
https://github.com/scieloorg/opac/issues/1393
N/A
> Apresenta marcadores nos itens do histórico

- packtools/catalogs/htmlgenerator/v2.0/article-meta.xsl
Esse PR implementa a visualização do **DOI** do idioma corrente e não somente o DOI do idioma principal, como descrito no TK scieloorg/opac#1391
Pelo Arquivo
`packtools/catalogs/htmlgenerator/v2.0/article-meta.xsl`
Vc pode editar um xml mult-language SPS e adicionar dentro da tag `<front-stub>` as tags abaixo
```xml
<article-meta>
<article-id pub-id-type="doi">10.1590/NUMERO DO DOI</article-id>
</article-meta>
```
Arquivo xml e html utilizado para o teste
[packtools_tk_opac_1391.zip](https://github.com/scieloorg/packtools/files/3531357/packtools_tk_opac_1391.zip)
PT-BR
EN
scieloorg/opac#1391
- scieloorg/Web#689
- https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/sub-article.html
> Exibição do DOI de tradução na página do artigo scieloorg/opac#1391

- packtools/catalogs/htmlgenerator/v2.0/article-meta-related-article.xsl
- packtools/catalogs/htmlgenerator/v2.0/config-labels.xml
- tests/test_htmlgenerator.py
Este Pull Request implementa o quadro de destaque para documentos que retratam outros documentos assim como já acontecia com documentos que são erratas.
- `packtools/catalogs/htmlgenerator/v2.0/article-meta-related-article.xsl` L `20`
Para testar esse PR manualmente deve-se:
- Fazer o download de algum documento XML que é do tipo `retraction` (fixture em anexo);
- Executar o `htmlgenerator`;
- Verificar a caixa amarela no html gerado.
N/A
scieloorg/opac/issues/1400
N/A
[2236-8906-hoehnea-45-03-0540.txt](https://github.com/scieloorg/packtools/files/3579441/2236-8906-hoehnea-45-03-0540.txt)
> Adiciona destaque para a retratação de documentos

- packtools/catalogs/htmlgenerator/v2.0/article-meta-related-article.xsl
- packtools/catalogs/htmlgenerator/v2.0/config-labels.xml
- tests/test_htmlgenerator.py
Este PR altera os labels utilizados para a retratação de documentos de acordo com o comentário https://github.com/scieloorg/opac/issues/1406#issuecomment-524839144. Também adiciona suporte para retratações parciais como indicado pela SPS https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/1.9-branch/narr/retratacao.html.
- `packtools/catalogs/htmlgenerator/v2.0/config-labels.xml` L `340`
Para testar esse PR manualmente deve-se:
- Fazer o download de algum documento XML que é do tipo `retraction` (fixture em anexo);
- Executar o `htmlgenerator`;
- Verificar a caixa amarela no html gerado.
N/A
scieloorg/opac/issues/1400
N/A
[2236-8906-hoehnea-45-03-0540.txt](https://github.com/scieloorg/packtools/files/3579441/2236-8906-hoehnea-45-03-0540.txt)
> Adiciona suporte a retratações parciais e atualiza labels de retratação

- packtools/catalogs/htmlgenerator/v2.0/article-meta-related-article.xsl
- tests/test_htmlgenerator.py
Corrige o link para o artigo retratado considerando que pode ser formado pelo PID e/ou SciELO ID, além do DOI
packtools/catalogs/htmlgenerator/v2.0/article-meta-related-article.xsl
`python setup.py test -s tests.test_htmlgenerator.HTMLGeneratorTests`
Ao acessar
https://www.scielosp.org/article/rcsp/2016.v42n4/663-663/
O link:
Deve ser
https://www.scielosp.org/article/S0864-34662016000200003
no lugar de
https://doi.org/S0864-34662016000200003
n/a
#207 
n/a
> Corrige o link para o artigo retratado considerando que pode ter outro padrão

- packtools/webapp/custom_filters.py
- requirements.txt
- setup.py
Remove dependência da lib _python-slugify_, que deixou de suportar a versão 3.4 do Python e resulta em erros no CI. 
Verificando que a lib não é utilizada em mais nenhum lugar além de ` packtools/webapp/custom_filters.py`.
1. Inicialize a aplicação web, com os comandos:
```bash
$ export APP_SETTINGS=packtools.webapp.config.default.ProductionConfig
$ export FLASK_APP=packtools.webapp.app.py
$ flask run
```
2. Acesse http://127.0.0.1:5000 -> Stylechecker, e valide um XML SciELO PS
3. Verifique com o inspetor de códigos que o atributo _class_ do elemento `<label>` possui o valor `label label-style-error`. A função `slugify` era utilizada para produzir `label-style-error`.
Esta modificação faz com que o packtools volte a funcionar no Python 3.4.
#211 
Faz com que o PR #209 passe no Travis-CI, …
> Remove dependência da lib python-slugify

- packtools/catalogs/__init__.py
- packtools/catalogs/scielo-style-1.10.sch
- tests/test_schematron_1_10.py
Adiciona validação do conjunto de URLs parte da taxonomia CRedIT para SciELO PS 1.10.
Sugiro o módulo de testes.
Será necessário obter um XML SciELO PS, se assegurar que a versão em `article[@specific-use = 'sps-1.10']`, e manipular os valores de `contrib/role/@content-type`.
n/a
n/a
#218 
https://github.com/scieloorg/scielo_publishing_schema/blob/3b9184bf185fe43c0a134e0da618ddfcf46c4f40/docs/source/narr/taxonomia-credit.rst
> Adiciona validação das URLs do CRediT na versão 1.10 do SciELO PS

- packtools/__init__.py
- packtools/catalogs/htmlgenerator/v2.0/article-text-alternatives.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-fig.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-formula.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-graphic.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-table.xsl
- packtools/catalogs/htmlgenerator/v2.0/html-modals-figs.xsl
- packtools/exceptions.py
- packtools/package_optimiser.py
- packtools/utils.py
- requirements.txt
- setup.py
- tests/test_htmlgenerator.py
- tests/test_utils.py
Cria uma cópia otimizada de pacotes SPS para WEB. Para cada documento em XML do pacote, são criadas imagens alternativas às imagens em formato TIFF e thumbnails para serem exibidos na página de artigos. Essas imagens, junto com a imagem original, são incluídas como alternativas no XML.
Também é possível executar a otimização de pacotes SPS através do comando `package_optimiser`.
Por fim, também implementa as alterações no HTMLGenerator para ler as imagens alternativas, dando prioridade para as otimizadas `scielo-web`.
É recomendado que a revisão seja feita por commits.
- Instale os `requirements.txt` e a nova versão
- Com um pacote SPS em arquivo compactado ZIP, execute o comando:
```bash
package_optimiser --loglevel INFO <caminho para o pacote SPS>
```
- Confira também as opções do …
> Otimizador de pacotes SPS para WEB

- packtools/catalogs/htmlgenerator/v2.0/article-meta.xsl
- tests/test_htmlgenerator.py
Este pull request faz com que o DOI exibido no topo da página do artigo seja encapsulado em uma tag `a `;
- `packtools/catalogs/htmlgenerator/v2.0/article-text-ref.xsl`
Para testar este pull request manualmente, deve-se:
- Transforme o XML em um html utilizando o HTMLgenerator;
Obrigado @robertatakenaka.
N/A
N/A
[Diretrizes do Crossref](https://docs.google.com/document/d/1K3Lj031Q6LqYxo33Byh0EzywskO-ywkKg526ENqYa54/edit#)
> Aplica diretrizes do Crossref durante a transformação de XML em HTML

- .travis.yml
- packtools/utils.py
- packtools/version.py
- requirements.txt
- setup.py
- tests/test_utils.py
- tox.ini
Retira o suporte à versão 3.4 do Python, além de corrigir alguns teste unitários que estavam quebrando e atualizar as versões do lxml por conta do suporte à versão 3.7.
É recomendado que seja feita por commits.
- Execute o tox.
- Observe que as a versão 3.4 não está mais sendo testada.
- Observe que as versões testadas da lxml agora são da 4.2 em diante.
Com a implementação do otimizador de imagens (#216), os problemas com a falta de suporte à versão 3.4 do Python das dependências foi o que determinou esta alteração. Por conta da quantidade de testes unitários, este teste leva bastante tempo.
N/A
#216
Suporte do Pillow às versões Python: https://pillow.readthedocs.io/en/stable/installation.html
> Retira suporte à versão do Python 3.4 e corrige testes

- packtools/__init__.py
- packtools/exceptions.py
- packtools/package_optimiser.py
- packtools/utils.py
- tests/test_utils.py
Este PR reestrutura o otimizador de pacotes SPS e deixa pública a otimização de XMLs. Com isso, é possível:
* Fazer a otimização de um arquivo XML com seus ativos digitais através do uso da interface pública da biblioteca, sem a necessidade de estar em um pacote SPS em arquivo compactado
* Parar o processo de otimização caso algum erro ocorra: arquivo não encontrado, erro no arquivo de imagem original
* Facilitar a manutenção
É recomendado que a revisão seja feita por commits.
- Instale os `requirements.txt` e a nova versão
- Com um pacote SPS em arquivo compactado ZIP, execute o comando:
```bash
package_optimiser --loglevel INFO <caminho para o pacote SPS>
```
- Confira também as opções do comando:
```bash
package_optimiser --help
```
- Um pacote otimizado deve ter sido gerado
- Com os …
> Reestruturação do otimizador de pacotes SPS

- packtools/utils.py
Quando formatos de arquivos não são suportados pelo Pillow, uma exceção será lançada e, por isso, este tratamento se faz necessário no otimizador de XMLs para que, de acordo com o atributo `stop_if_error`, a execução seja ou não interrompida. Também foram adicionados logs de debug.
É recomendado que a revisão seja feita por commits.
1. Com um pacote SPS contendo arquivos SVG e documento referenciando-os, utilize o comando `package_optimiser` com a opção `--stopiferror`
2. A execução da otimização deve ser interrompida
3. Repita o comando acima sem a opção `--stopiferror`
4. A execução não deve ser interrompida, somente deve haver o log do problema.
Erro detectado durante a execução do DS Migração de XMLs nativos.
n/a
#227 
.
> Trata erros na criação de instância de conversor de imagens na otimização de XMLs

- packtools/utils.py
Este PR altera o otimizador WEB para que ele faça a leitura dos XMLs sem o carregamento da DTD no parser. Também foi feito ajuste em mensagem do comando do otimizador e a inclusão do DOCTYPE no retorno da otimização, quando já existente no documento.
Em `packtools/utils.py`.
Com um pacote SPS, comprimido em arquivo ZIP, que contenha documentos XML inválidos pela DTD:
1. Execute o comando `package_optimiser <caminho do pacote SPS>`
2. Observe que o documento e seus ativos digitais são otimizados sem erros
Este problema foi identificado durante o processo de migração da coleção BR.
n/a
https://github.com/scieloorg/document-store-migracao/issues/317
.
> Ajusta leitura de XMLs no otimizador para que seja independente da DTD

- .travis.yml
- packtools/utils.py
- setup.py
- tests/test_utils.py
Este PR trata exceção lançada pelo Pillow para imagens que ultrapassem as  dimensões limite definida em `Image.MAX_IMAGE_PIXELS` na classe geradora de imagens renderizáveis em WEB. Este tratamento foi incluído na criação de objeto Image por bytes lidos de arquivo, na conversão para PNG e criação de thumbnail à partir de arquivo lido de _path_ informado.
É recomendado que a revisão seja feita por commits.
- Com um pacote SPS contendo um arquivo de imagem que ultrapasse 178.956.970 pixels de dimensões, execute o comando:
```
package_optimiser <caminho-para-pacote-SPS>
```
- A execução do comando deve ser completada com sucesso e mensagem de erro deve ser exibida
- Rode novamente o comando adicionando o argumento `--stopiferror`
- A exceção `packtools.exceptions.WebImageGeneratorError` deve …
> Trata exceção lançada pelo Pillow para prevenção de ataques DOS

- packtools/catalogs/scielo-style-1.10.sch
- tests/test_schematron_1_10.py
Este PR inclui novamente as validações de URLs da taxonimia CRediT de acordo com as definições mais recentes.
n/a
Você poderá produzir manualmente um XML que contém a estrutura da taxonomia. Alguns exemplos poderão ser encontrados em https://docs.google.com/document/d/1UwHgZc-99cnRlg5lfbLMPAbfWmDLmgMYY1fxgdh9ScI/edit?usp=sharing.
n/a
n/a
#218 
https://docs.google.com/document/d/1UwHgZc-99cnRlg5lfbLMPAbfWmDLmgMYY1fxgdh9ScI/edit?usp=sharing
> Adiciona novamente as validações de URLs CRediT

- packtools/catalogs/scielo-style-1.10.sch
- tests/test_schematron_1_10.py
Adiciona regras de validação definidas na versão 1.0 da SciELO PS para pareceres abertos e taxonimia CRediT.
Penso que pelos códigos de testes.
Não será fácil, mas caso queira muito terá que preparar arquivos XML (que podem ser encontrados no diretório _tests/samples_) com as estruturas documentadas em https://docs.google.com/document/d/18ZiEUSqbxGlh0IprIUJF-N54m6ni7NXzVfjH9xc6DFw/edit?usp=sharing e https://docs.google.com/document/d/1UwHgZc-99cnRlg5lfbLMPAbfWmDLmgMYY1fxgdh9ScI/edit?usp=sharing.
A integração destes códigos é pré-requisito para o lançamento da SciELO PS 1.10.
n/a
n/a
* https://docs.google.com/document/d/18ZiEUSqbxGlh0IprIUJF-N54m6ni7NXzVfjH9xc6DFw/edit?usp=sharing
* https://docs.google.com/document/d/1UwHgZc-99cnRlg5lfbLMPAbfWmDLmgMYY1fxgdh9ScI/edit?usp=sharing.
> Adiciona regras de pareceres e CRediT para SciELO PS 1.10

- packtools/catalogs/htmlgenerator/v2.0/article-text-alternatives.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-fig.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-graphic.xsl
- packtools/version.py
- tests/test_htmlgenerator.py
Adiciona o uso da imagem de thumbnail na página do artigo, ajusta a prioridade para também utilizar imagens sem o atributo ``specific-use``.  
Olhando os commits. 
Rodando os testes unitários com: 
```shell 
python setup.py test
```
Ou somente o módulo alterado: 
```shell 
python -m unittest discover -s tests -p "test_html*.py"
```
No tíquete referente a esse PR é possível obter dois xmls, onde temos a situação de imagens com e sem o atributo ``specific-use``. 
Utilizando o comando ``htmlgenerator --nochecks {XML}`` é possível verificar o resultado no HTML resultante. 
Importante ter em mente a priorização acordado entre a equipe no tíquete: https://github.com/scieloorg/opac/issues/1643 (Comentários)
N/A
Tíquete referente a esse PR: https://github.com/scieloorg/opac/issues/1643 
Utilizei …
> Adiciona o uso da imagem de thumbnail na página do artigo, ajusta a prioridade para utilizar imagens sem o atributo ``specific-use``.

- packtools/catalogs/htmlgenerator/v2.0/article-text-alternatives.xsl
- tests/test_htmlgenerator.py
Dentre as alternativas, seleciona o elemento `graphic` também considerando o valor do atributo `@xlink:href`, que não pode ser "vazio"
por commits
Use o pacote em anexo, ou crie um pacote XML de acordo com a descrição mencionada no issue #236
Execute:
```bash
python htmlgenerator.py --loglevel DEBUG <arquivo xml> 
```
[tk236 2.zip](https://github.com/scieloorg/packtools/files/5257496/tk236.2.zip)
No zip, coloquei duas situações:
- `<graphic xlink:href="fig.png"/><graphic xlink:href="fig.jpg"/>` (apresentação fica melhor)
- `<graphic xlink:href="fig.jpg"/><graphic xlink:href="fig.png"/>` 
A lógica é pegar o primeiro `<graphic/>` que satisfaça a condição de ter `@xlink:href` diferente de `''`.
n/a
#236
n/a
> Seleciona o elemento `graphic` também considerando o valor do atributo `@xlink:href`, que não pode ser "vazio"

- packtools/catalogs/htmlgenerator/v2.0/article-text-alternatives.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-fig.xsl
- packtools/catalogs/htmlgenerator/v2.0/html-modals-figs.xsl
- packtools/catalogs/htmlgenerator/v2.0/html-modals.xsl
Revisa e amplia a apresentação do elemento "fig" em vários contextos (front, body, back, sub-article)
por commits
```shell
python packtools/htmlgenerator.py --loglevel DEBUG <path de xml> --nochecks --nonetwork
```
onde `<path de xml>` é o caminho do arquivo xml
Resultado do htmlgenerator do master (atual)
[master_antes_de_tk237 2.zip](https://github.com/scieloorg/packtools/files/5392400/master_antes_de_tk237.2.zip)
Resultado do htmlgenerator tk237_novo
[tk237 2.zip](https://github.com/scieloorg/packtools/files/5392401/tk237.2.zip)
havia bug também no modal que agrupa figura, tabela e fórmulas
Não foram revisadas as apresentações de tabelas e equações. No mesmo arquivo tk236b.xml, há amostras de variações da apresentação atual destes elementos. Mas acredito que merecem uma revisão.
n/a …
> Revisa e amplia a apresentação do elemento "fig" em vários contextos (front, body, back, sub-article)

- packtools/catalogs/htmlgenerator/v2.0/article-meta.xsl
- packtools/catalogs/htmlgenerator/v2.0/article.xsl
- packtools/catalogs/htmlgenerator/v2.0/html-modals-how2cite.xsl
Corrige as datas na página do artigo, considerando a SPS 1.9.
A partir da SPS 1.9 (2019) as datas são representadas com
`pub-date[@date-type]` no lugar de `pub-date[@pub-type]`
Os valores para @date-type são pub e collection que são correpondentes
respectivamente a
`pub-date/@pub-type == epub-ppub, collection, ppub` equivalem a
`@date-type='collection'`
`pub-date/@pub-type == epub` equivalem a @date-type='pub' conjuntamente
com `@publication-format='electronic'`
packtools/catalogs/htmlgenerator/v2.0/article.xsl:187
[1807-5762-icse-23-e170521-com-collection.zip](https://github.com/scieloorg/packtools/files/3154300/1807-5762-icse-23-e170521-com-collection.zip)
```xml
<pub-date pub-type="epub">
<day>14</day>
<month>02</month>
<year>2019</year>
</pub-date>
<pub-date …
```
> Corrige as datas na página do artigo, considerando a SPS 1.9

- packtools/catalogs/htmlgenerator/v2.0/html-modals.xsl
Este PR aplica o modal para figuras, mesmo sem atributo `@id`. Atualmente, caso a tag `fig` não possua o atributo, não é aberto o modal para exibir a versão original da imagem.
Commit 6289c9f.
1. Obtenha um XML que contenha a tag `fig` sem atributo `id` e ativo digital, como o exemplo abaixo:
2. Execute o comando `htmlgenerator <caminho do XML> --nochecks`
3. Abra o(s) HTML(s) gerados
4. Verifique se a imagem do thumbnail é exibida no modal ao clicar nela.
Para os casos onde haja mais de uma tag `fig` sem `id`, ainda haverá quebra, sendo necessário corrigir o XML.
.
https://github.com/scieloorg/opac/issues/1654
.
> Corrige exibição de imagem ampliada de figuras sem ID no XML

- packtools/catalogs/htmlgenerator/v2.0/article-meta-abstract.xsl
Este PR altera aplicação de template XSL para os resumos, que separava o que era `abstracts` e `trans-abstracts` de `article` e `sub-article`. Agora, aplica o template para todos os abstracts e trans-abstracts de forma que todos sempre serão apresentados na página do texto completo, independente do idioma.
Commit 2085d82.
1. Obtenha um artigo em XML com texto completo em 2 idiomas e com resumos em diferentes idiomas, inclusive dos textos completos. Exemplo no anexo [1]
2. Execute o comando `htmlgenerator <caminho para o XML> --nochecks`
3. Abra os HTMLs gerados
4. Verifique a apresentação de todos os resumos nos 2 HTMLs
[1] - …
> Altera XSL do artigo para apresentar todos os resumos no texto completo

- packtools/catalogs/htmlgenerator/v2.0/article-meta-abstract.xsl
- tests/test_htmlgenerator.py
Faz a verificação da quantidade de resumos e de títulos de resumos para colocar âncora e título para resumos. Também inclui testes unitários.
Commit 730d8e1.
1. Obtenha um XML sem resumos
2. Gere HTML usando o comando `htmlgenerator <caminho para o XML> --nochecks`
3. Verifique se o HTML não possui título de resumos
4. Obtenha XMLs com um ou mais resumos e sem títulos
5. Execute o passo 2 para cada XML
6. Verifique a presença de título
7. Obtenha XMLs com um ou mais resumos e respectivos títulos
5. Execute o passo 2 para cada XML
6. Verifique se o HTML não possui título de resumos
Este problema foi identificado após a inclusão de todos os resumos na página do artigo.
.
#215 
.
> Corrige verificação para colocar título em seção de resumo

- packtools/catalogs/htmlgenerator/v2.0/article-meta-abstract.xsl
- packtools/catalogs/htmlgenerator/v2.0/article.xsl
- packtools/catalogs/htmlgenerator/v2.0/config-vars.xsl
- packtools/domain.py
- packtools/htmlgenerator.py
- tests/samples/article-abstract-and-trans-abstract.xml
- tests/samples/article-abstract-en-sub-articles-pt-es.xml
- tests/test_htmlgenerator.py
Gerar um HTML que apresente somente o resumo de um dado idioma
por commits
Execute
```console
python packtools/htmlgenerator.py file --gs_abstract
```
Testar com artigos com 1 resumo, artigos com mais de um resumo, artigos com sub-article que tenham resumo.
Não gerará o link para o texto completo, nem o link para os demais resumos conforme o ticket https://github.com/scieloorg/opac/issues/1762. Isso deve ficar  como responsabilidade do site.
n/a
#246 e https://github.com/scieloorg/opac/issues/1762
n/a
> Gera um HTML que apresente somente o resumo de um dado idioma

- packtools/domain.py
Resolve um problema inerente das linguagens produzidas pelo SGML.
Insere espaços antes e depois do comentário de forma a evitar a mensagem de erro de que existe `-` no final do comentário.
Insere espaço entre `--` (`- -`) para evitar a mensagem de erro de existe `--` dentro do comentário
por commits
ver issue #254
packtools é usado no XC e o erro ocorreu durante o processamento de um documento.
n/a
#254
n/a
> Modifica conteúdo de comentário para evitar exceção ValueError

- packtools/catalogs/htmlgenerator/v2.0/article-text-table.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-xref.xsl
Corrige a apresentação de `graphic` que aparecem dentro de `table` e de `inline-graphic` que aparecem dentro de `xref`
por commits
Execute 
```
python packtools/htmlgenerator.py --nonetwork --nochecks <arquivo>
```
Sendo `<arquivo>` o caminho do arquivo XML.
Ver sugestões de arquivos nos issues: #248 e #250
n/a
n/a
#248, #250
n/a
> Corrige a apresentação de `graphic` que aparecem dentro de `table` e de `inline-graphic` que aparecem dentro de `xref`

- HISTORY.md
- packtools/catalogs/htmlgenerator/v2.0/article-meta-abstract.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-list.xsl
- packtools/version.py
- setup.py
Corrige várias questões nos resumos:
- garantir que apresentação de _highlights_ tem que ser antes dos demais resumos
- os _highlights_ não tem palavras-chaves
- o primeiro resumo está com as palavras-chaves em idioma incorreto (isso só ocorre nos XML cujo grupo de palavras chaves está em ordem diferente da dos resumos)
- artigo não tem resumo, mas apresenta o título "Abstract" (isso ocorre porque no XML tem a tag `<abstract/>` vazia)
por commits
executando:
```console
python packtools/htmlgenerator.py --loglevel DEBUG --nonetwork --nochecks arquivo.xml
````
n/a
[tk265.zip](https://github.com/scieloorg/packtools/files/6641198/tk265.zip)
#265
closes #217
n/a
> Corrige várias questões nos resumos

- HISTORY.md
- packtools/catalogs/htmlgenerator/v2.0/article-text-xref.xsl
- packtools/version.py
Considera outros elementos além de `sup` em `xref`
por commits
Executando:
```console
python packtools/htmlgenerator.py --loglevel DEBUG --nonetwork --nochecks nauplius.xml
```
[Arquivo Comprimido.zip](https://github.com/scieloorg/packtools/files/6730103/Arquivo.Comprimido.zip)
n/a
n/a
#267
n/a
> Considera outros elementos além de `sup` em `xref`

- README.md
- packtools/catalogs/htmlgenerator/v2.0/article-text-fig.xsl
- packtools/version.py
- tests/test_htmlgenerator.py
- tests/test_utils.py
Esse PR altera a forma de apresentar as imagens na página dos artigo do OPAC.
Por commit
Rodando os testes: 
```
python setup.py test
```
ou 
```
python setup.py test -s tests.test_htmlgenerator
```
Também nesse PR adicionei como rodar o comando do **htmlgenerator** e uma documentação dos testes.
A nova forma de apresentar as imagens: 
```html 
<a href="" data-toggle="modal" data-target="#ModalFigf03">
<div class="thumbImg">
<div class="zoom"><span class="sci-ico-zoom"></span></div>
</div>
</a>
```
N/A
Esse tíquete está relacionado com a atividade: #270 e com a alteração da interface: https://github.com/scieloorg/opac/pull/2035
N/A
> Alterar o HTML do artigo para conter tags image ao invés de imagens como background. 

- packtools/catalogs/htmlgenerator/static/scielo-article-standalone.css
- packtools/catalogs/htmlgenerator/v2.0/article-text-alternatives.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-formula.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-mathml.xsl
- packtools/catalogs/htmlgenerator/v2.0/article.xsl
- packtools/catalogs/htmlgenerator/v2.0/config-vars.xsl
- packtools/version.py
Corrige a apresentação de fórmulas na página do artigo
por commits
```console
python packtools/htmlgenerator.py --nochecks --nonetwork --loglevel DEBUG /Users/roberta.takenaka/xml_packages/com-equcoes.xml
```
[com-equcoes.xml.zip](https://github.com/scieloorg/packtools/files/8174954/com-equcoes.xml.zip)
TODO: 
- fazer o htmlgenerator receber parâmetros e passar para a XSL
- Atualmente só funciona com `tex-math`. Não está surtindo efeito para `mml:math`
- Será necessário atualizar no opac o endereço do javascript que renderiza as fórmulas 
n/a
https://github.com/scieloorg/opac/issues/2063
https://docs.mathjax.org/en/latest/web/start.html
https://docs.mathjax.org/en/latest/input/tex/index.html
https://docs.mathjax.org/en/latest/input/mathml.html
> Corrige a apresentação de fórmulas na página do artigo

- packtools/catalogs/htmlgenerator/v2.0/article-text-fig.xsl
- packtools/version.py
- tests/test_htmlgenerator.py
Corrige apresentação de figuras (bug inserido ao tentar resolver questões de preservação)
Por commits
```console
python packtools/htmlgenerator.py --nochecks --nonetwork --loglevel DEBUG /Users/roberta.takenaka/xml_packages/com-equcoes.xml
```
*Correto*
```html
<div class="row fig" id="f1">
<a name="f1"></a>
<div class="col-md-4 col-sm-4">
<a href="" data-toggle="modal" data-target="#ModalFigf1">
<div class="thumbImg">
<div class="zoom"><span class="sci-ico-zoom"></span></div>
</div>
</a>
</div>
<div class="col-md-8 col-sm-8">
<strong></strong><br>
Plots of the WBXII density with s = 1.
</div>
</div>
```
*Incorreto*
```html
<div class="row fig" id="f1">
<a name="f1"></a>
<div class="col-md-4 col-sm-4">
<a href="https://minio.scielo.br/documentstore/1678-2690/vR75PXVgmxtML8Fx6q6vTbR/17badab …
```
> Corrige apresentação de figuras (bug inserido ao tentar resolver questões de preservação)

- tests/sps/test_sps_maker.py
Faz uma pequena correção em alguns testes de sps, a saber:
1. Renomeia chave `temp-zip` para `zip` (de modo a repercutir o que foi alterado no módulo sps_maker)
2. Corrige exceção esperada em alguns testes (de `SPSDownloadXMLError` para `SPSHTTPResourceNotFoundError`)
Por commits.
Basta executar o teste manualmente, como em: `python setup.py test -s tests.sps`
Este PR apenas inclui alguns códigos-fonte que deveriam ter sido incluídos no PR anterior (#281). Há alguns testes com falha que estão relacionados com html-generator e que não possuem relação com este PR ou o anterior (vide **Figura 1**).
**Figura 1**. Testes com falha herdados de outros PRs.
N/A
N/A
> Corrige testes de sps

- packtools/catalogs/htmlgenerator/v2.0/article-text-mathml.xsl
- packtools/catalogs/htmlgenerator/v2.0/config-vars.xsl
- packtools/version.py
- tests/fixtures/mmlmath/f.xml
Corrige a apresentação de fórmulas representadas por `mml:math`, removendo o namespace das tags, desta forma os navegadores conseguem renderizá-las. No entanto, nem todos os navegadores conseguem.
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/math acessado nesta data
por commits
```console
python packtools/htmlgenerator.py --nochecks --nonetwork --loglevel DEBUG tests/fixtures/mmlmath/f.xml
```
n/a
https://github.com/scieloorg/opac/issues/2231
Exemplos: 
https://www.scielo.br/j/mr/a/nnBRGz6Rc3nYKcyrLsDCLRt/?lang=en#
https://www.scielo.br/j/rbef/a/Tr6nFmXB9F5zsBkxfsRMpXd …
> Corrige a apresentação de fórmulas representadas por `mml:math`

- packtools/catalogs/htmlgenerator/v2.0/article-text-fig.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-formula.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-table.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-xref.xsl
- packtools/catalogs/htmlgenerator/v2.0/html-modals-scheme.xsl
- packtools/catalogs/htmlgenerator/v2.0/html-modals-tables.xsl
- packtools/catalogs/htmlgenerator/v2.0/html-modals.xsl
- packtools/version.py
- tests/fixtures/dot_in_id/arquivo.xml
- tests/fixtures/dot_in_id/tabelas.xml
Troca o caracter ponto por `_` se aparece no `@id` de figura, equações e tabelas para que funcione a apresentação dos "modais". Tendo o caracter ponto, o JavaScript não funciona conforme esperado.
por commits
```console
python packtools/htmlgenerator.py --nochecks --nonetwork --loglevel DEBUG tests/fixtures/dot_in_id/tabelas.xml
```
```console
python packtools/htmlgenerator.py --nochecks --nonetwork --loglevel DEBUG tests/fixtures/dot_in_id/arquivo.xml
```
n/a
n/a
https://github.com/scieloorg/opac/issues/2233
n/a
> Troca o caracter ponto por `_` se aparece no `@id` de figura, equações e tabelas

- packtools/sps/models/article_assets.py
- packtools/version.py
- tests/sps/fixtures/2318-0889-tinf-33-e200068.xml
- tests/sps/test_article_assets.py
Este PR adiciona o campo/property "type" em um Asset. A ideia é permitir que quem chame ArticleAssets.article_assets seja capaz de saber o tipo (original, miniatura, otimizado) de cada asset. 
No momento, esses tipos são obtidos com base na presença/ausência dos atributos "content-type" e "specific-use" nas tags que representam os assets.
Por commits.
Tenha uma instância instalada do packtools e faça algo como:
```python
from packtools.sps.models.article_assets import ArticleAssets
with open('data.xml') as fin:
aa = ArticleAssets(fin)
for a in aa.article_assets:
print(a.name, a.type, a.id)
```
Quando o asset não for uma imagem, será considerado, por exclusão, como "original" (dado que não haverá os atributos `specific-use` e `content-type`. Isso pode ser ajustado facilmente, caso seja …
> Adiciona campo type em classe Asset

- packtools/sps/models/article_renditions.py
- packtools/version.py
- tests/sps/test_article_renditions.py
Cria um módulo article_renditions.py que contém as classes ArticleRenditions e Rendition. Essas classes são responsáveis por inferir, a partir de um lxml.etree, quais são os idiomas (e portanto, arquivos PDF) esperados para um documento (etree).
Por commits.
```python
from packtools.sps.models.article_renditions import ArticleRenditions
from packtools.sps.utils import xml_utils
fin = open('arquivo.xml')
xmltree = xml_utils.get_xml_tree(fin.read())
ar = ArticleRenditions(xmltree)
for i in ar.article_renditions:
print(i.language, i.is_main_language)
```
Poderia ser interessante tentar inferir qual seria o nome do arquivo em si, para cada idioma, no entanto, isto depende dos outros campos estarem preenchidos (ISSN, Ano, etc...). Também poderia ser com base no nome do arquivo, mas acredito …
> Adiciona classe ArticleRenditions

- packtools/sps/models/article_errata.py
- packtools/version.py
- tests/sps/test_article_errata.py
Cria modelos para representar elementos Erratum existentes em documentos XML corrigidos ou alterados por Errata.
Por commits.
N/A
Esta alteração faz parte da issue 51 do repositório scms-upload. Especificamente, as alterações realizadas neste PR permitirão que os novos modelos sejam utilizados no scms-upload para enviar e avaliar XML com ArticleErrata e com RelatedArticle.
N/A
https://github.com/scieloorg/scms-upload/issues/51
Modelagem esperada de uma errata: https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/narr/errata.html
> Adiciona modelos ArticleErrata e Erratum

- packtools/sps/models/article_assets.py
- tests/sps/test_article_assets.py
Adiciona uma função `name_canonical` que retorno nome de asset em formato padronizado ou canônico: package_name-sufixo-extensão.
Por commits.
N/A
1. Ainda neste ponto do PR estamos lidando apenas com XML, por isso acho pertinente que a função nova fique em article_assets; Mas cabe mudança para outra estrutura/módulo, se assim julgarmos.
2. Este PR ajudará na implementação do milestone JOURNAL-2A  do scms-upload;
N/A
N/A
N/A
> Adiciona função que retorna nome oficial de asset

- packtools/sps/exceptions.py
- packtools/sps/models/front_journal_meta.py
- packtools/sps/validation/article.py
- packtools/sps/validation/journal.py
- packtools/version.py
- tests/sps/test_front_journal_meta.py
- tests/sps/validation/test_journal.py
Adiciona validação relacionada a XML e dados de periódico.
Por commits.
...
Este PR faz parte das alterações necessárias para lidar com o envio de pacotes com conteúdo inédito na aplicação scms-upload. Alguns pontos devem ser considerados neste PR. Por exemplo, que critérios queremos adotar para indicar que um xml não correspondente ao que temos registrado. 
1. Caso um XML tenha um ISSN correto e outro estranho em relação à lista de issns questionada, devemos indicar que há algo errado? 
2. Isso vale para outros campos como acrônimo e título de periódico, quero dizer, o quão diferente podemos aceitar.
N/A
N/A
N/A
> Adiciona validação de conteúdo de xml com dados de periódico

- packtools/sps/models/front_journal_meta.py
- packtools/version.py
- tests/sps/validation/test_journal.py
Corrige método que valida se os códigos ISSN que existem num XML são compatíveis com aqueles esperados.
Por commits.
N/A
O método que recupera ISSN de um XML retorna None quando este campo não existe no XML. A correção passou por fazer esse método retornar string vazia.
N/A
N/A
N/A
> Corrige validação de códigos ISSN

- packtools/sps/validation/article_and_subarticles.py
- packtools/version.py
- tests/sps/validation/test_article_and_subarticles.py
Corrige caso em que não há parâmetro xml:lang definido em <article> ou <sub-article>.
Por commits.
Como na PR anterior relacionado a validação de xml:lang.
Foi preciso fazer esse ajuste para melhor acomodar essa validação na aplicação scms-upload.
N/A
N/A
N/A
> Corrige situação de validador de xml:lang sem atributo

- packtools/catalogs/htmlgenerator/v2.0/article-text-fn.xsl
- packtools/version.py
- tests/fixtures/htmlgenerator/editor/1807-0205-paz-62-e202262026.en.html
- tests/fixtures/htmlgenerator/editor/1807-0205-paz-62-e202262026.xml
- tests/fixtures/htmlgenerator/editor/1982-7849-rac-26-06-e190379.en.html
- tests/fixtures/htmlgenerator/editor/1982-7849-rac-26-06-e190379.pt.html
- tests/fixtures/htmlgenerator/editor/1982-7849-rac-26-06-e190379.xml
Adiciona ao menu lateral esquerdo da página do artigo, as notas de rodapé.
O objetivo é destacar editor de seção, disponibilidade de dados de pesquisa, entre outros, a fim de explicitar práticas de Ciência Aberta.
por commits
Executando htmlgenerator
```console
htmlgenerator --nonetwork --nochecks tests/fixtures/htmlgenerator/editor/1982-7849-rac-26-06-e190379.xml
```
n/a
https://github.com/scieloorg/opac/issues/2451
https://github.com/scieloorg/opac/issues/2426
https://wp.scielo.org/wp-content/uploads/dados.pdf
> Adiciona ao menu lateral esquerdo da página do artigo, as notas de rodapé

- packtools/catalogs/htmlgenerator/v2.0/article-text-section-data-availability.xsl
- packtools/catalogs/htmlgenerator/v2.0/article.xsl
- packtools/catalogs/htmlgenerator/v2.0/config-labels.xml
- tests/fixtures/htmlgenerator/data-availability/hxcB3n9hzmSGz4v6dgzDsxp.en.html
- tests/fixtures/htmlgenerator/data-availability/hxcB3n9hzmSGz4v6dgzDsxp.pt.html
- tests/fixtures/htmlgenerator/data-availability/hxcB3n9hzmSGz4v6dgzDsxp.xml
Cria na página do artigo a seção "Dados de Pesquisa" para dar destaque às citações do tipo `data` ou `database` e também de material suplementar identificados dentro de `article-meta`.
por commits
Executando o comando:
```console
htmlgenerator --nonetwork --nochecks tests/fixtures/htmlgenerator/data-availability/hxcB3n9hzmSGz4v6dgzDsxp.xml
```
Não foram incluídos na seção "Dados de pesquisa", as notas de rodapé nem qualquer menção de dados suplementares no decorrer do texto, pois em ambos os casos, estes já fazem parte do texto corrido.
https://github.com/scieloorg/opac/issues/2506
https://wp.scielo.org/wp-content/uploads/dados.pdf
> Cria na página do artigo a seção "Dados de Pesquisa"

- packtools/catalogs/htmlgenerator/v2.0/article-meta-related-article.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-fn.xsl
- packtools/version.py
- tests/fixtures/htmlgenerator/affiliations/0006-8705-brag-81-e2022.en.html
- tests/fixtures/htmlgenerator/data-availability/hxcB3n9hzmSGz4v6dgzDsxp.en.html
- tests/fixtures/htmlgenerator/data-availability/hxcB3n9hzmSGz4v6dgzDsxp.pt.html
- tests/fixtures/htmlgenerator/editor/1807-0205-paz-62-e202262026.en.html
- tests/fixtures/htmlgenerator/editor/1982-7849-rac-26-06-e190379.en.html
- tests/fixtures/htmlgenerator/editor/1982-7849-rac-26-06-e190379.pt.html
- tests/fixtures/htmlgenerator/howtocite_without_foot_note/howtocite.en.html
- tests/fixtures/htmlgenerator/image_in_table/img_in_table.en.html
- tests/fixtures/htmlgenerator/modal_authors/96fDfzSqzxPF9cPxxPNYFmk.en.html
- tests/fixtures/htmlgenerator/modal_authors/96fDfzSqzxPF9cPxxPNYFmk.pt.html
- tests/fixtures/htmlgenerator/related-article/varias_erratas.en.html
- tests/fixtures/htmlgenerator/related-article/varias_erratas.pt.html
- tests/fixtures/htmlgenerator/related-article/x.pt.html
- tests/fixtures/htmlgenerator/translator/dqR6y8bPFVVQnxnFHY66ZZK.pt.html
Corrige fn and related article
- Apresenta somente fn do tipo edited-by e data-availability, de author notes
- Apresenta somente fn do tipo edited-by e data-availability, encontrados também em back e body 
- Apresenta 1 rótulo para cada related-article
por commits
```console
htmlgenerator --nonetwork --nochecks --loglevel DEBUG  tests/fixtures/htmlgenerator/data-availability/back.xml
htmlgenerator --nonetwork --nochecks --loglevel DEBUG  tests/fixtures/htmlgenerator/related-article/varias_erratas.xml
```
n/a
n/a
correções de #354 
n/a
> Corrige fn and related article

- packtools/catalogs/htmlgenerator/v2.0/generic-history.xsl
- packtools/version.py
- tests/fixtures/htmlgenerator/related-article/related_article_fake_preprint.pt.html
Apresenta na seção de histórico, o link do Preprint que não tem data do tipo preprint
por commits
```console
htmlgenerator --nonetwork --nochecks --loglevel DEBUG  tests/fixtures/htmlgenerator/related-article/related_article_fake_preprint.xml
```
n/a
#357 
https://github.com/scieloorg/opac/issues/2423
https://github.com/scieloorg/opac/issues/2424
n/a
> Apresenta na seção de histórico, o link do Preprint que não tem data do tipo preprint

- packtools/catalogs/htmlgenerator/v2.0/article-meta-related-article.xsl
- packtools/catalogs/htmlgenerator/v2.0/config-labels.xml
- packtools/file_utils_mimetype.py
- packtools/sps/models/article_ids.py
- packtools/sps/models/funding_group.py
- tests/fixtures/htmlgenerator/related-article/addendum.pt.html
- tests/fixtures/htmlgenerator/related-article/addendum.xml
- tests/sps/test_article_ids.py
- tests/test_funding_group.py
Faz correções de XSL:
- texto de relacionamento de adendos
Faz correções em classe que obtém dados de XML:
- sobre financiamento 
- ArticleIds
- mimetype
por commits
Texto do adendo
```shell
python packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG   tests/fixtures/htmlgenerator/related-article/addendum.xml
```
Sobre o texto do adendo o valor de `related-article-type="addendum"` em um `article/@article-type="addendum"` está inadequado, pois está indicando que é um adendo relacionado com outro. No entanto, foi feita esta decisão para evitar criar novos valores para este atributo, mas causa "conflito". Então, para a solução apropriado, considerou o valor de `article/@article-type="addendum"` para decidir se o texto é **This addendum adds information to the following …
> Faz na apresentação de relacionamento de adendo e correções nas classes de obtenção de dados de XML SPS

- packtools/sps/models/article_authors.py
- tests/sps/test_article_authors.py
Adicionada a extração da tag role com namespace na classe Authors para obter informações sobre o papel do autor.
Por commit
`python setup.py test -s .\tests\sps\test_article_authors.py`
N/A
N/A
N/A
N/A
> Adicionada a extração da tag role com namespace na classe Authors

- packtools/sps/models/article_license.py
- packtools/sps/validation/article_license.py
- tests/sps/test_article_license.py
- tests/sps/validation/test_article_license.py
Adiciona uma classe para acessar os dados de licença de uso, bem como a respectiva classe de validação e testes.
Por _commit_.
Rodar os testes:
`python3 -m unittest -v tests/sps/test_article_license.py`
`python3 -m unittest -v tests/sps/validation/test_article_license.py` 
NA.
NA.
TK #385 e TK #343 
NA.
> Article license

- packtools/sps/validation/article_authors.py
- tests/sps/validation/test_article_authors.py
Cria validação e teste para a tag <role> e o namespace content-type
Por commit
`python setup.py test -s .\tests\sps\validation\test_article_authors.py`
N/A
N/A
[#376](https://github.com/scieloorg/packtools/issues/376) [#326](https://github.com/scieloorg/packtools/issues/326) [#386](https://github.com/scieloorg/packtools/issues/386)
> Validação e teste  da tag <role> e content-type.

- packtools/sps/models/article_authors.py
- requirements.txt
- tests/sps/test_article_authors.py
Corrige a obtenção de rid de aff em autor que pode ser ausente
por commits
Executando o teste automatizado com o comando:
```console
python -m unittest -v -k Witho
```
n/a
n/a
n/a
n/a
> Corrige a obtenção de rid de aff em autor que pode ser ausente

- packtools/sps/models/article_titles.py
- packtools/sps/utils/xml_utils.py
- tests/sps/models/test_article_titles.py
- tests/sps/utils/test_xml_utils.py
Adiciona em ArticleTitles o título do artigo padronizado, sem tags e sem espaços extras
Por commits
Executando os comandos
```console
python -m unittest -v -k XMLU
python -m unittest -v -k article_titl
```
Demanda para pid_provider conseguir comparar os artigos usando o título padronizado
n/a
n/a
n/a
> Adiciona em ArticleTitles o título do artigo padronizado, sem tags e sem espaços extras

- packtools/sps/models/article_abstract.py
- packtools/sps/utils/xml_utils.py
- tests/sps/models/test_article_abstract.py
Corrige a classe Abstract que facilita o acesso aos resumos do XML SciELO.
A implementação anterior tinha alguns problemas:
- exigia que os resumos sempre tem `sec`;
- considera que sub-article e trans-abstract ocorrem mais de 1 vez;
- os nomes dos métodos não refletem o que fazem e não há comentários que facilitem a compreensão;
- uso de dicionário quando é melhor usar lista de dicionário;
por commits
Executando os testes automatizados
```console
python -m unittest -v -k  article_abstr
```
Ou instanciando a class Abstract (packtools.sps.models.article_abstract)
Para manter a compatibilidade com os usuários da classe, alguns métodos não foram eliminados.
É necessário refatorar os códigos usuários e, então, eliminar os métodos sem uso.
n/a
#384
n/a
> Corrige a classe Abstract que facilita o acesso aos resumos do XML SciELO

- packtools/sps/models/aff.py
- packtools/sps/models/article_authors.py
- tests/sps/models/test_aff.py
- tests/sps/models/test_article_authors.py
- tests/sps/validation/test_article_authors.py
Faz com que Authors retorne as afiliações junto aos dados de autores
por commits
Instanciando a classe Authors
Já existe a classe AffiliationExtractor, mas o seu retorno me pareceu muito complexo, pois instituição é uma lista de dicionário de um item, e isso ocorre também com country.
Estas classes tem como objetivo simplificar o acesso ao conteúdo do XML.
n/a
n/a
n/a
> Faz com que Authors retorne as afiliações junto aos dados de autores

- packtools/sps/models/article_authors.py
- packtools/sps/pid_provider/xml_sps_lib.py
Corrige o código para considerar que alguns atributos estão ausentes como contrib-type de contrib e href de related-article.
Por commits
Usando as respectivas classes com XMLs nas situações indicadas.
https://www.scielo.br/j/rgo/a/xqJTxHGKRyW3yNHtdZnV7bw/?format=xml
```xml
<related-article id="pr03" related-article-type="press-release" specific-use="processing-only"/>
```
Problema identificado ao executar provide pids para scielo.br
n/a
n/a
n/a
> Fix pid provider absent href and absent contrib type

- packtools/sps/models/article_authors.py
- packtools/sps/models/article_ids.py
- packtools/sps/pid_provider/xml_sps_lib.py
Corrige retorno de pub_year.
Também garante que os valores atribuídos para v2, v3 e aop_pid tem tamanho definido
Por commits
Instanciando ArticleDates com um XML  que possui somente `<pub-date pub-type="epub"/>`.
Ajustes para uso no pid_provider. Impedimento de registro de artigo que possui somente "article date".
n/a
n/a
n/a
> Corrige retorno de XMLWithPre.pub_year

- packtools/sps/models/article_assets.py
- packtools/sps/models/article_authors.py
- packtools/sps/models/v2/article_assets.py
- tests/sps/models/test_article_assets.py
- tests/sps/models/test_article_assets_v2.py
Cria versão 2 da classe ArticleAssets para manipular os ativos digitais do XML.
A anterior estava mais complexa e havia defeito ao gerar o nome de ativos digitais para o pacote SPS.
por commits
Instanciando a classe e fazendo uso.
Executando:
```console
python -m unittest -v -k test_article_assets_v2
```
A classe anterior foi mantida, pois provavelmente estava em uso em Upload / upload
Esta nova classe será usada em Upload / migration
n/a
n/a
n/a
> Cria versão 2 da classe ArticleAssets para manipular os ativos digitais do XML

- packtools/sps/models/article_authors.py
Corrige o método `Authors.contribs_with_affs` para evitar exceção `KeyError: 'aff_rids'`
por commits
Instancie a classe usando um XML sem `xref`, por exemplo:
```xml
<contrib xmlns:xlink="http://www.w3.org/1999/xlink" contrib-type="author">
<name>
<surname>Portela-Lindoso</surname>
<given-names>Ana Ang&#233;lica Bulc&#227;o</given-names>
</name>
</contrib>
```
e use o método `contribs_with_affs`
n/a
```
[2023-09-22 11:43:44,668: ERROR/ForkPoolWorker-4] Task publication.tasks.task_publish_article[fc96120e-4419-46ee-91ad-5e4b795790de] raised unexpected: KeyError('aff_rids')
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 477, in trace_task
R = retval = fun(*args, **kwargs)
File …
```
> Corrige o método `Authors.contribs_with_affs` para evitar exceção `KeyError: 'aff_rids'`

- packtools/catalogs/htmlgenerator/v2.0/article-text-list.xsl
Corrige apresentação de lista do tipo "simple"
Por commits
Tenha um XML contendo:
```xml
<list list-type="simple">
<list-item>
<p>2.1. FALTA DE VISÃO SOBRE HIERARQUIA DE FONTES PARA PESQUISA.</p>
</list-item>
<list-item>
<p>2.2. HEGEMONIA DA DOUTRINA E ABUSO DE CITAÇÕES DE MANUAL.</p>
</list-item>
<list-item>
<p>2.3. USO ADVOCATÍCIO DAS FONTES (ESPECIALMENTE JULGADOS): CITAÇÃO DE JULGADOS QUE CONFIRMAM UMA TESE, SEM PESQUISA SISTEMÁTICA DE JURISPRUDÊNCIA QUE MOSTRE SUA RELEVÂNCIA E REPRESENTATIVIDADE.</p>
</list-item>
<list-item>
<p>2.4. MAU USO DO DIREITO COMPARADO: COMPARAÇÃO SEM MÉTODO E FORA DE CONTEXTO.</p>
</list-item>
</list>
```
Execute o htmlgenerator
```console
python packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG  lista_simple.xml
```
n/a
antes
depois …
> Corrige apresentação de lista do tipo "simple" (version_python27)

- packtools/sps/validation/article_and_subarticles.py
- tests/sps/validation/test_article_and_subarticles.py
Adiciona função de validação para idiomas de documentos.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_and_subarticles.py
`
NA.
NA.
NA.
NA.
> Validate article lang

- packtools/sps/models/article_and_subarticles.py
- packtools/sps/validation/article_and_subarticles.py
- packtools/sps/validation/article_xref.py
- packtools/translator.py
- tests/sps/models/test_article_and_subarticles.py
- tests/sps/validation/test_article_and_subarticles.py
- tests/sps/validation/test_article_xref.py
Refatora o procedimento de validação para o elemento `xref`, atributos `rid` e `id`, para adequação do retorno em um formato padronizado.
Por _commit_.
Avaliando os testes propostos:
`python3 -m unittest -v tests/sps/validation/test_article_xref.py`
O objetivo principal deste PR é o entendimento comum sobre um formato padronizado de retorno das funções de validação.
NA.
NA.
NA.
> Validate xref

- packtools/catalogs/htmlgenerator/v2.0/article-text-fn.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-section-data-availability.xsl
- packtools/catalogs/htmlgenerator/v2.0/config-labels.xml
- tests/fixtures/htmlgenerator/data-availability/skq7h8xjdNPvWzykLBVLJwz.en.3_0.html
- tests/fixtures/htmlgenerator/data-availability/skq7h8xjdNPvWzykLBVLJwz.en.html
- tests/fixtures/htmlgenerator/data-availability/skq7h8xjdNPvWzykLBVLJwz.pt.3_0.html
- tests/fixtures/htmlgenerator/data-availability/skq7h8xjdNPvWzykLBVLJwz.pt.html
- tests/fixtures/htmlgenerator/data-availability/skq7h8xjdNPvWzykLBVLJwz.xml
Resolve apresentação de fn[@fn-type='data-availability'] e da seção que destaca a disponibilidade de dados
por commits
Executando:
```console
python packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG  tests/fixtures/htmlgenerator/data-availability/skq7h8xjdNPvWzykLBVLJwz.xml
```
n/a
n/a
https://github.com/scieloorg/opac/issues/2844
n/a
> [opac | python27] Resolve apresentação de fn[@fn-type='data-availability'] e da seção que destaca a disponibilidade de dados

- packtools/sps/validation/article_xref.py
- packtools/sps/validation/exceptions.py
Corrige nome de classe de exceão que impacta nos testes
Por _commit_
`python3 -m unittest -v tests/sps/validation/*`
Após a correção do nome os testes não estão quebrando:
```
python3 -m unittest -v tests/sps/validation/*
tests/sps/validation/__pycache__ (unittest.loader._FailedTest) ... ERROR
test_affiliation_without_original (tests.sps.validation.test_aff.AffiliationValidationTest) ... ok
test_affiliations_without_city (tests.sps.validation.test_aff.AffiliationValidationTest) ... ok
test_affiliations_without_country (tests.sps.validation.test_aff.AffiliationValidationTest) ... ok
test_affiliations_without_country_code (tests.sps.validation.test_aff.AffiliationValidationTest) ... ok
test_affiliations_without_orgname (tests.sps.validation.test_aff.AffiliationValidationTest) ... ok …
```
> Corrige nome de classe de exceção

- packtools/catalogs/htmlgenerator/v2.0/html-modals-contribs.xsl
Página do Artigo - Adiciona apresentação de contrib/bio
Por commits
Executando htmlgenerator para o pacote mencionado em https://github.com/scieloorg/opac/issues/2856
```console
python packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG path_do_xml
```
n/a
https://github.com/scieloorg/opac/issues/2856
https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/bio.html
> Página do artigo - apresentação de contrib/bio

- packtools/sps/validation/article_and_subarticles.py
- tests/sps/validation/test_article_and_subarticles.py
Adiciona classe de validação para `article-id-other.`
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_and_subarticles.py`
NA.
NA.
NA.
NA.
> Article id other validation

- packtools/sps/models/dates.py
- tests/sps/models/test_dates.py
Corrige a identificação de `<date pub-type="epub"/>` como sendo data do tipo collection por não ser completa.
Na versão SPS 1.8 era possível epub representar data de fascículo e também de artigo, dependendo se era completa ou incompleta.
por commits
```console
python3 -m unittest -v tests/sps/models/test_dates.py
```
n/a
n/a
n/a
https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt-br/1.7-branch/tagset/elemento-pub-date.html
https://www.scielo.br/j/abo/a/xwsWKQNn8K7LpbNyXqydyzd/?format=xml
> Pid provider article date

- packtools/catalogs/htmlgenerator/v3.0/article-text-xref.xsl
Modifica a apresentação de `xref[@ref-type="bibr"]` condicionado a `ref-list/ref/label` que significa que são referências numeradas
https://www.scielo.br/j/ocr/a/JmwhLpWvrmHTdCtJsmHh6CM/?lang=en
Buscar:
```
( Clements et al., 2022, 2023)
```
n/a
n/a
Relacionado com https://github.com/scieloorg/packtools/pull/519
n/a
> Modifica a apresentação de xref[@ref-type="bibr"] (python3)

- packtools/sps/models/article_data_availability.py
- packtools/sps/validation/article_data_availability.py
- packtools/sps/validation/exceptions.py
- tests/sps/models/test_article_data_availability.py
- tests/sps/validation/test_article_data_availability.py
Adiciona procedimento de validação para declaração de disponibilidade de dados.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_data_availability.py`
NA.
NA.
NA.
https://wp.scielo.org/wp-content/uploads/dados.pdf
> Data availability validation

- packtools/sps/validation/exceptions.py
- packtools/sps/validation/journal_meta.py
- tests/sps/validation/test_journal_meta.py
Refatora o procedimento de validação para ISSN's de modo a atender ao padrão adotado para validações.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_journal_meta.py`
NA.
NA.
NA.
NA.
> Fix: adaptar a classe de validação de ISSN's ao padrão adotado

- packtools/catalogs/htmlgenerator/v2.0/article-text-section-data-availability.xsl
Remove a duplicidade de apresentação da seção de disponibilidade de dados
Isso ocorre porque há tanto a seção como também o elemento supplementary-material Neste caso, a lógica foi se há seção, não faz nada, pois na apresentação do texto, naturalmente a seção será apresentada. Além disso, desconsiderar a apresentação de article-meta/supplementary-material.
por commits
Executando:
```console
python packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG arquivo.xml
```
n/a
n/a
https://github.com/scieloorg/opac/issues/2878
n/a
> Remove a duplicidade de apresentação da seção de disponibilidade de dados

- packtools/sps/validation/article_doi.py
- tests/sps/validation/test_article_doi.py
Adiciona procedimento de validação para a verificação se o DOI é registrado. Além disso, padroniza o retorno de outras funções de validação, envolvendo DOI, para retornarem uma lista de dicionários ao invés de um único dicionário. Essa última atualização tem por objetivo padronizar os retornos das funções de validação.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_doi.py`
NA.
NA.
NA.
NA.
> Doi registered

- packtools/sps/validation/article_authors.py
- tests/sps/validation/test_article_authors.py
Adiciona validações para verificação se o elemento ORCID é único e possui registro válido.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_authors.py`
NA.
NA.
NA.
NA.
> Feat: adiciona validações para ORCID

- packtools/sps/models/kwd_group.py
- tests/sps/models/test_kwd_group.py
Modifica modelo, de obtenção de palavras-chave e idiomas correspondentes, para tratar ausência de idioma em `<kwd-group>`.
Por _commit_.
`python3 -m unittest -v tests/sps/models/test_kwd_group.py`
NA.
NA.
TK #534 
NA.
> Fix: Missing sub-article keyword lang

- packtools/sps/models/article_abstract.py
- tests/sps/models/test_article_abstract.py
Adiciona a verificação da existência de `<abstract>` em `<sub-article>`.
Por _commit_
`python3 -m unittest -v tests/sps/models/test_article_abstract.py`
O erro, identificado na Issue #535, é decorrente da ausência de `<abstract>` em `<sub-article>`. A sugestão de tratamento desse erro é baseada na verificação da existência de `<abstract>` antes da tentativa de obtenção. Dessa forma, o resultado da função é o que segue:
```
[
{'lang': 'pt', 'abstract': 'FUNDAMENTO: A relação entre atividade inflamatória e pró-trombótica na cardiomiopatia chagásica e em outras etiologias é obscura. OBJETIVO: Estudar o perfil de marcadores pró-trombóticos e pró-inflamatórios em pacientes com insuficiência cardíaca chagásica e compará-los com os de etiologia não chagásica. MÉTODOS: Coorte transversal. …
```
> Fix: abstract missing in sub-article

- packtools/sps/pid_provider/xml_sps_adapter.py
- packtools/sps/pid_provider/xml_sps_lib.py
Adiciona o parâmetro pretty_print=False para tostring() em XMLWithPre e PidProviderXMLAdapter
Por commits
```python
>>> from packtools.sps.pid_provider.xml_sps_lib import get_xml_with_pre
>>> x = get_xml_with_pre("<root><a>dlafdjafj<b>djadlfjlafj</b></a></root>")
>>> x.tostring()
'<root>\n  <a>dlafdjafj<b>djadlfjlafj</b></a>\n</root>\n'
>>> x = get_xml_with_pre("<root><a>dlafdjafj <b>djadlfjlafj</b></a></root>")
>>> x.tostring()
'<root>\n  <a>dlafdjafj <b>djadlfjlafj</b></a>\n</root>\n'
```
n/a
n/a
n/a
n/a
> Adiciona o parâmetro pretty_print=False para tostring() em XMLWithPre e PidProviderXMLAdapter

- packtools/catalogs/htmlgenerator/v2.0/article-text-fn.xsl
- packtools/catalogs/htmlgenerator/v3.0/article-text-fn.xsl
Corrige ausência de apresentação do rótulo dentro da seção "Edited by"
por commits
```console
python3 packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG  edited-by-twice.xml
```
n/a
https://github.com/scieloorg/opac/issues/2892
n/a
> Corrige ausência de apresentação do rótulo dentro da seção "Edited by"

- packtools/catalogs/htmlgenerator/v2.0/article-text-fn.xsl
Corrige ausência de apresentação do rótulo dentro da seção "Edited by"
por commits
```console
python3 packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG  edited-by-twice.xml
```
n/a
https://github.com/scieloorg/opac/issues/2892
n/a
> Corrige ausência de apresentação do rótulo dentro da seção  'Edited by'

- packtools/sps/formats/crossref.py
- packtools/sps/formats/crossref_generator.py
- packtools/sps/formats/oai_dc.py
- packtools/sps/formats/oai_dc_agris.py
- packtools/sps/formats/pmc.py
- packtools/sps/formats/pmc_generator.py
- packtools/sps/formats/pubmed.py
- packtools/sps/formats/pubmed_generator.py
Modifica pmc_pipeline, pubmed_pipeline e crossref_pipeline para retornar str no lugar de xmltree, para facilitar o uso da função, para que a função cliente não tenha que lidar com a árvore de XML.
por commits
Executando os scripts de packtools/sps/formats: crossref_generator.py, pmc_generator.py, pubmed_generator.py
n/a
n/a
n/a
n/a
> Modifica pmc_pipeline, pubmed_pipeline e crossref_pipeline para retornar str no lugar de xmltree

- packtools/sps/formats/crossref.py
- packtools/sps/formats/crossref_generator.py
- packtools/sps/formats/oai_dc.py
- packtools/sps/formats/oai_dc_agris.py
- packtools/sps/formats/pmc.py
- packtools/sps/formats/pmc_generator.py
- packtools/sps/formats/pubmed.py
- packtools/sps/formats/pubmed_generator.py
Modifica pmc_pipeline, pubmed_pipeline e crossref_pipeline para retornar str no lugar de xmltree, para facilitar o uso da função, para que a função cliente não tenha que lidar com a árvore de XML.
por commits
Executando os scripts de packtools/sps/formats: crossref_generator.py, pmc_generator.py, pubmed_generator.py
n/a
n/a
n/a
n/a
> Modifica pmc_pipeline, pubmed_pipeline e crossref_pipeline para retornar str no lugar de xmltree (2)

- packtools/sps/models/article_abstract.py
- packtools/sps/models/article_titles.py
- packtools/sps/models/kwd_group.py
- packtools/sps/utils/xml_utils.py
- packtools/sps/validation/article_lang.py
- tests/sps/models/test_article_abstract.py
- tests/sps/models/test_article_titles.py
- tests/sps/models/test_kwd_group.py
- tests/sps/validation/test_article_lang.py
Adiciona procedimento de validação para:
- Verificação da existência de `title`;
- Verificação da existência de `abstract` sem `keywords`;
- Verificação da existência de `keywords` sem `abstract`;
- Verificação da correspondência entre os idiomas dos elementos anteriormente descritos. 
Por _commit_, preferencialmente iniciando pelos testes.
`python3 -m unittest -v tests/sps/validation/test_article_lang.py`
NA.
NA.
NA.
NA.
> Feat: adiciona procedimento de validação para idiomas correspondentes

- packtools/sps/models/funding_group.py
- packtools/sps/validation/funding_group.py
- tests/sps/models/test_funding_group.py
- tests/sps/validation/test_funding_group.py
Adiciona procedimento de validação para informações sobre financiamento, especificamente:
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_funding_group.py`
[Fonte: scielo publishing schema](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt-br/latest/tagset/elemento-award-group.html#elemento-award-group)
NA.
NA.
NA.
> Feat: adiciona validação para informações de financiamento

- packtools/sps/models/article_abstract.py
- packtools/sps/utils/xml_utils.py
- tests/sps/models/test_article_abstract.py
- tests/sps/models/test_xml_utils.py
Modifica a obtenção de textos para desconsiderar `subtags.`
Por _commit_.
`python3 -m unittest -v tests/sps/models/test_article_abstract.py`
NA.
NA.
TK #556 
NA.
> Fix: abstract with subtags

- packtools/sps/utils/xml_utils.py
- tests/sps/models/test_xml_utils.py
Corrige problemas identificados pelos testes:
1. Nó é `None` em `get_node_without_subtag`;
2. Tratamento de `namespaces`, ex.: de `<{http://www.w3.org/1998/Math/MathML}mrow>` para `<mml:mrow>`;
3. Manutenção dos atributos de um **nó**, quando este **nó** não for removido.
Por _commit_.
Avaliar os testes.
NA.
NA.
NA.
NA.
> Fix: corrige problemas identificados pelos testes

- packtools/sps/pid_provider/xml_sps_adapter.py
- packtools/sps/pid_provider/xml_sps_lib.py
Add order (`article-id[@pub-id-type="other"]`) setter and getter
por commits
```python
from packtools.sps.pid_provider.xml_sps_lib import XMLWithPre
from packtools.sps.pid_provider.xml_sps_adapter import PidProviderXMLAdapter
from lxml import etree
for x in XMLWithPre.create(path="/Users/roberta.takenaka/github.com/scieloorg/packtools_/packtools_python3/packtools/tests/fixtures/htmlgenerator/table_wrap_group_and_fig_group/QMyWZTMgngWRCDtVJfJH9Cn/QMyWZTMgngWRCDtVJfJH9Cn.xml"):
a = PidProviderXMLAdapter(x, x.sps_pkg_name)
print(a.order)
a.order = a.v2[-5:]
```
Foi identificado ausência do article-id conforme esperado ao carregar XML no Upload dos países
n/a
n/a
n/a
> Add order (`article-id[@pub-id-type="other"]`) setter and getter

- packtools/sps/models/article_citations.py
- packtools/sps/validation/article_citations.py
- packtools/sps/validation/exceptions.py
- tests/sps/models/test_article_citations.py
- tests/sps/validation/test_article_citations.py
Adiciona classe de validação para referências, considerando: obrigatório `year`, `source`, `article-title` (se `publication-type=journal`), pelo menos um autor (institucional ou não), tipo da citação (valor)
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_citations.py`
NA.
NA.
NA.
NA.
> Feat: validate element citation

- packtools/sps/validation/aff.py
- tests/sps/validation/test_aff.py
Padroniza o retorno das funções de validação de afiliações para funcionarem como geradoras.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_aff.py`
NA.
NA.
TK #568 
NA.
> Refactor: padroniza funções como geradoras (aff)

- packtools/sps/validation/article_and_subarticles.py
- tests/sps/validation/test_article_and_subarticles.py
Padroniza o retorno das funções de validação de artigos para funcionarem como geradoras.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_and_subarticles.py`
NA.
NA.
TK #568 
NA.
> Refactor: padroniza funções como geradoras (article and sub-article)

- packtools/sps/validation/article_and_subarticles.py
- packtools/sps/validation/article_authors.py
- tests/sps/validation/test_article_and_subarticles.py
- tests/sps/validation/test_article_authors.py
Padroniza o retorno das funções de validação de autores para funcionarem como geradoras.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_authors.py`
NA.
NA.
TK #568 
NA.
> Refactor: padroniza funções como geradoras (article authors)

- packtools/sps/validation/article_and_subarticles.py
- packtools/sps/validation/article_doi.py
- tests/sps/validation/test_article_and_subarticles.py
Padroniza o retorno das funções de validação de DOI para funcionarem como geradoras.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_doi.py
`
NA.
NA.
TK #568 
NA.
> Refactor: padroniza funções como geradoras (article doi)

- packtools/catalogs/htmlgenerator/v2.0/article-meta-contrib.xsl
Troca http para https nos links de orcid, lattes e researchid
por commits
Executando o comando htmlgenerator
```console
python packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG  path_de_xml.xml
```
Observe o link para o orcid após clicar no botão Autoria ou Authorship abaixo do título do artigo. Observe que o link é montado com https no lugar de http.
n/a
n/a
n/a
n/a
> Troca http para https nos links de orcid, lattes e researchid

- packtools/catalogs/htmlgenerator/v2.0/article-meta-contrib.xsl
Troca http para https nos links de orcid, lattes e researchid
por commits
Executando o comando htmlgenerator
```console
python packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG  path_de_xml.xml
```
Observe o link para o orcid após clicar no botão Autoria ou Authorship abaixo do título do artigo. Observe que o link é montado com https no lugar de http.
n/a
n/a
n/a
n/a
> Troca http para https nos links para orcid, lattes e researcherid

- packtools/sps/pid_provider/xml_sps_lib.py
Adiciona em XMLWithPre, os atributos data e files
Por commits
Instanciando XMLWithPre e executando XMLWithPre.create e .data
```
>>> from packtools.sps.pid_provider.xml_sps_lib import XMLWithPre
>>> from lxml import etree
>>> x = XMLWithPre("", etree.fromstring("<article/>"))
>>> x.data
{'sps_pkg_name': '', 'pid_v3': None, 'pid_v2': None, 'aop_pid': None, 'filename': None, 'files': None}
```
```
from packtools.sps.pid_provider.xml_sps_lib import XMLWithPre
from lxml import etree
for x in XMLWithPre.create(path='/Users/roberta.takenaka/1519-9940-rbspa-25-0224.zip'):
print(x.data)
```
```
{'sps_pkg_name': '2448-2455-jpe-34-e3440', 'pid_v3': None, 'pid_v2': None, 'aop_pid': None, 'filename': '2448-2455-jpe-34-0223/2448-2455-jpe-34-e3440.xml', 'files': ['2448-2455-jpe-34-0223/', …
```
> Adiciona em XMLWithPre, os atributos data e files

- packtools/sps/models/alternatives.py
- packtools/sps/validation/alternatives.py
- packtools/sps/validation/exceptions.py
- packtools/sps/validation/utils.py
- tests/sps/models/test_alternatives.py
- tests/sps/validation/test_alternatives.py
Adiciona modelo e validação para `<alternatives>`.
Por _commit_.
`python3 -m unittest -v tests/sps/models/test_alternatives.py`
`python3 -m unittest -v tests/sps/validation/test_alternatives.py`
NA.
NA.
TK #607 
NA.
> Feat: alternatives validation

- packtools/catalogs/htmlgenerator/v2.0/article-meta-abstract.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-back.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-fn.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-section-data-availability.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-sub-article.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text.xsl
- packtools/catalogs/htmlgenerator/v2.0/generic-history.xsl
- packtools/catalogs/htmlgenerator/v2.0/generic-pub-date.xsl
Às vezes o menu esquerdo não é gerado adequadamente. Foi identificado que é necessário que existe no `div` os dois atributos juntos: `class="articleSection" e data-anchor="título da seção no menu"`. Havia casos de `class="articleSection"` sem o correspondente `data-anchor="título da seção no menu"`, então o link era levado a uma âncora incorreta.
por commits
```console
python packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG  arquivo.xml
```
n/a
n/a
#614 
n/a
> [página artigo v2.0] Corrige links do menu esquerdo

- packtools/catalogs/htmlgenerator/v2.0/article-meta-abstract.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-back.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-fn.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-section-data-availability.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-sub-article.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-xref.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text.xsl
- packtools/catalogs/htmlgenerator/v2.0/generic-history.xsl
- packtools/catalogs/htmlgenerator/v2.0/generic-pub-date.xsl
- packtools/catalogs/htmlgenerator/v3.0/article-meta-abstract.xsl
- packtools/catalogs/htmlgenerator/v3.0/article-text-ref.xsl
- packtools/catalogs/htmlgenerator/v3.0/article-text-section-data-availability.xsl
- packtools/catalogs/htmlgenerator/v3.0/generic-history.xsl
- packtools/catalogs/htmlgenerator/v3.0/generic-pub-date.xsl
Corrige geração das âncoras do menu esquerdo da página do artigo para layout v3.0
por commits
Executando:
```console
python packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG arquivo.xml
```
Só foi necessário atualizar a v2.0
n/a
https://github.com/scieloorg/opac_5/issues/134
n/a
> Corrige geração das âncoras do menu esquerdo da página do artigo para layout v3.0

- packtools/sps/models/article_contribs.py
- tests/sps/models/test_article_contribs.py
Adiciona uma nova classe `Contrib` que permite a análise e extração de informações detalhadas de autores a partir de dados XML estruturados. A classe `Contrib` oferece várias propriedades e métodos que facilitam o acesso a diversos elementos de contribuição, tais como identificadores, nome, colaboração, referências cruzadas e papéis dos autores.
Funcionalidades incluídas:
- Tipo de Contribuição (`contrib_type`): Obtém o atributo `contrib-type` do elemento `<contrib>`.
- Identificadores de Contribuição (`contrib_ids`): Extrai todos os identificadores de contribuição (`contrib-id`) e seus respectivos tipos.
- Nome do Contribuidor (`contrib_name`): Obtém as partes do nome do contribuidor, incluindo `surname`, `given-names`, `prefix` e `suffix`.
- Autoria Institucional (`collab`): Extrai o …
> Refactor: adiciona classe 'Contrib' para analisar informações de autores em XML

- packtools/sps/validation/journal_meta.py
- tests/sps/validation/test_journal_meta.py
Este PR modifica classes e métodos para a validação de elementos específicos no metadado de periódicos em XML, especificamente focando nos nomes dos editores (publisher-name) e nos IDs NLM TA (journal-id). Essas validações garantem que os valores nos elementos XML estejam conforme o esperado, ajudando a manter a consistência e a precisão dos dados. Ele resolve problemas de validação de dados de metadados em XML para publicações científicas, assegurando que os nomes dos editores e IDs NLM TA sejam precisos e correspondam aos valores esperados.
A revisão pode começar nas seguintes classes:
- `PublisherNameValidation`
- `JournalIdValidation`
- `JournalMetaValidation`
- `PublisherTest`
-` JournalIdValidationTest`
- `JournalMetaValidationTest`
`python3 -m unittest -v …
> Chore: standardize journal meta validation

- packtools/sps/validation/utils.py
- requirements.txt
- tests/sps/validation/test_utils.py
Este Pull Request adiciona uma nova função `get_doi_information` que consulta a API da CrossRef para obter informações detalhadas sobre um DOI, incluindo títulos e autores. A função detecta o idioma dos títulos e estrutura os dados de forma organizada. Também foram incluídos testes unitários para garantir o correto funcionamento da função.
O revisor deve iniciar a leitura do código a partir dos seguintes arquivos:
- `packtools/sps/validation/utils.py (contendo a função get_doi_information)`
- `tests/test_doi_information.py (contendo os testes unitários)`
Para testar manualmente esta funcionalidade, siga os passos abaixo:
1. Garanta que as dependências listadas no arquivo requirements.txt estejam instaladas.
2. Utilize a função get_doi_information com um DOI válido e verifique se a …
> Feat: get doi information

- packtools/sps/models/article_doi_with_lang.py
- packtools/sps/validation/article_doi.py
- tests/sps/models/test_article_doi_with_lang.py
- tests/sps/validation/test_article_doi.py
Este Pull Request implementa uma nova funcionalidade para validação de DOIs em artigos XML. Ele adiciona métodos para:
- Verificar a existência de DOIs.
- Garantir que todos os DOIs sejam únicos.
- Validar que os DOIs estejam registrados e correspondam aos metadados esperados (título, autores).
Essas funcionalidades visam solucionar problemas relacionados à inconsistência e duplicidade de DOIs, garantindo a integridade dos dados nos artigos XML.
Sugiro iniciar pela avaliação dos testes:
- `tests/sps/models/test_article_doi_with_lang.py`
- `tests/sps/models/test_article_doi_with_lang.py`
`python3 -m unittest -v tests/sps/validation/test_article_doi.py
`
NA
NA
NA
NA
> Chore: standardize article doi

- packtools/sps/validation/tablewrap.py
- tests/sps/validation/test_tablewrap.py
Este PR adiciona validação para a existência de elementos `<table-wrap>` em um documento XML. Ele introduz a classe `TableWrapValidation` para verificar se os elementos `<table-wrap>` estão presentes no XML fornecido e produz mensagens de validação apropriadas.
O revisor deve começar pela classe `TableWrapValidation` no arquivo `packtools/sps/validation/tablewrap.py`. Em seguida, prosseguir para revisar os casos de teste no arquivo `tests/sps/validation/test_tablewrap.py`.
`python3 -m unittest -v tests/sps/validation/test_tablewrap.py
`
NA
NA
NA
NA
> Feat: adds validation tablewrap

- packtools/sps/validation/fig.py
- tests/sps/validation/test_fig.py
Este PR adiciona validação para a existência de elementos `<fig>` em um documento XML. Ele introduz a classe FigValidation para verificar se os elementos `<fig>` estão presentes no XML fornecido e produz mensagens de validação apropriadas.
O revisor deve começar pela classe `FigValidation` no arquivo `packtools/sps/validation/fig.py`. Em seguida, prosseguir para revisar os casos de teste no arquivo `tests/sps/validation/test_fig.py`.
`python3 -m unittest -v tests/sps/validation/test_fig.py`
NA
NA
NA
NA
> Feat: adds validation fig

- packtools/sps/validation/formula.py
- tests/sps/validation/test_formula.py
Este PR adiciona validação para a existência de elementos `<disp-formula>` e `<inline-formula>` em um documento XML. Ele introduz a classe `FormulaValidation` para verificar se os elementos `<disp-formula>` e `<inline-formula>` estão presentes no XML fornecido e produz mensagens de validação apropriadas.
O revisor deve começar pela classe `FormulaValidation `no arquivo `packtools/sps/validation/formula.py`. Em seguida, prosseguir para revisar os casos de teste no arquivo `tests/sps/validation/test_formula.py.`
`python3 -m unittest -v tests/sps/validation/test_formula.py`
NA
NA
NA
NA
> Feat: adds validation formula

- packtools/sps/models/app_group.py
- packtools/sps/validation/app_group.py
- tests/sps/models/test_app_group.py
- tests/sps/validation/test_app_group.py
Este PR adiciona a validação para a existência de elementos `<app>` dentro de um grupo `<app-group>` em documentos XML. A validação garante que todos os elementos `<app>` esperados estejam presentes e fornece feedback apropriado quando esses elementos estão ausentes. Além disso, foi introduzida a classe `AppGroup` para gerenciar e extrair dados dos elementos `<app-group>` e `<app>`.
O revisor deve começar pelos arquivos:
`packtools/sps/validation/app.py para ver a implementação da classe AppValidation.`
`packtools/sps/models/app_group.py para verificar a nova classe AppGroup`.
`tests/sps/validation/test_app.py para verificar os testes unitários da validação de <app>`.
1. Carregue um documento XML com a estrutura de artigo (<`article>`).
2. Assegure-se de que o documento XML tenha um grupo …
> Feat: adds validation app

- packtools/sps/models/app_group.py
- packtools/sps/models/supplementary_material.py
- packtools/sps/validation/supplementary_material.py
- tests/sps/models/test_supplementary_material.py
- tests/sps/validation/test_supplementary_material.py
Este PR adiciona a implementação do modelo e a validação para elementos `<supplementary-material>` e `<inline-supplementary-material>` em artigos XML. Inclui também a criação dos testes unitários para garantir a extração correta de atributos desses elementos e a validação de sua existência no documento XML.
Recomenda-se começar a revisão pelos arquivos:
- `models/supplementary_material.py`
- `validation/supplementary_material.py`
- `tests/models/test_supplementary_material.py`
- `tests/validation/test_supplementary_material.py`
`python3 -m unittest -v tests/sps/models/test_supplementary_material.py`
Essas modificações são importantes para garantir que materiais suplementares associados a artigos científicos sejam corretamente identificados e validados, assegurando a integridade dos dados …
> Feat: adds supplementary material validation

- packtools/sps/models/app_group.py
- packtools/sps/models/media.py
- packtools/sps/validation/media.py
- tests/sps/models/test_media.py
- tests/sps/validation/test_media.py
Este PR adiciona a validação para os elementos `<media>` em documentos XML no contexto SciELO. A validação garante que os elementos `<media>` estejam presentes no documento e extrai informações relevantes, como `mimetype`, `mime-subtype` e `xlink:href`. Também foram adicionados testes unitários para verificar a correta extração e validação desses elementos, incluindo a presença de elementos `<media>` em sub-artigos.
Os revisores podem começar pelos seguintes arquivos:
- `models/media.py`
- `validation/media.py`
- `tests/models/test_media.py`
- `tests/validation/test_media.py`
Execute os testes unitários para garantir que todas as validações e extrações estejam funcionando conforme o esperado:
`python3 -m unittest -v tests/sps/models/test_media.py`
`python3 -m unittest -v …
> Feat: adds media validation

- packtools/sps/validation/dates.py
- tests/sps/validation/test_dates.py
Este PR corrige a validação de datas futuras na verificação do campo "collection date". A modificação garante que o valor obtido para o ano de coleção seja corretamente convertido para um número inteiro antes de comparar com a data futura. Essa correção evita erros de comparação de tipos e assegura que a validação funcione conforme esperado.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_dates.py`
NA
NA
TK #658 
NA
> Fix: fixes future date validation

- packtools/sps/models/v2/article_toc_sections.py
- packtools/sps/validation/article_toc_sections.py
- tests/sps/models/test_article_toc_sections.py
- tests/sps/validation/test_article_toc_sections.py
Este PR adiciona uma série de testes unitários para validar a funcionalidade da classe `ArticleTocSectionsValidation` do módulo `packtools.sps.validation.article_toc_sections`. Os testes cobrem diversos cenários para garantir a robustez e a precisão das validações realizadas pela classe. Especificamente, os testes visam:
- Verificar se as seções do TOC (Table of Contents) correspondem às seções esperadas.
- Garantir que o título do artigo seja diferente dos títulos das seções.
O revisor deve iniciar a leitura do código a partir do arquivo de testes:
`tests/sps/validation/test_article_toc_sections.py`
Para testar a funcionalidade manualmente, siga os passos abaixo:
1. Clone o repositório e navegue até a branch deste PR.
2. Certifique-se de ter as dependências instaladas (por exemplo, …
> Fix: subject validation

- packtools/sps/validation/article_contribs.py
- tests/sps/validation/test_article_contribs.py
Este PR modifica a função `validate_contribs_orcid_is_unique` para melhorar a validação da unicidade do ORCID entre autores em documentos XML. A modificação garante que ORCIDs repetidos não sejam considerados duplicados quando associados ao mesmo nome de autor. Isso corrige um problema onde autores com o mesmo nome e ORCID eram incorretamente marcados como duplicados.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_contribs.py
`
NA
NA
TK #681 
NA
> Fix: unique orcid validation

- packtools/sps/models/article_contribs.py
- tests/samples/example.xml
- tests/samples/example2.xml
- tests/sps/models/test_article_contribs.py
Este PR introduz uma nova função `contrib_full_name`, que é responsável por construir o nome completo de uma contribuição a partir das suas partes componentes, como prefixo, nomes, sobrenome e sufixo. A função percorre as diferentes partes do nome presentes no dicionário `contrib_name`, as concatena em uma string única, e retorna o nome completo, ou uma string vazia se nenhum componente estiver presente.
O revisor pode começar a leitura pelo arquivo onde a função `contrib_full_name` foi adicionada, especialmente na seção onde as funcionalidades relacionadas ao processamento de nomes de contribuições são implementadas.
1. Chame a função `contrib_full_name` em uma instância que contenha o atributo contrib_name populado com diferentes combinações de prefixo, nomes, sobrenome e sufixo.
2. …
> Fix: bug article contribs

- packtools/sps/models/fig.py
- packtools/sps/validation/fig.py
- tests/sps/models/test_fig.py
- tests/sps/validation/test_fig.py
Este Pull Request adiciona a validação da existência de elementos `<fig> `em documentos XML, além de incluir docstrings detalhadas para a classe `FigValidation` e seus métodos. Especificamente, ele:
- Introduz a classe `FigValidation` para validar a presença de elementos `<fig>` em documentos XML.
- Implementa o método `validate_fig_existence`, que gera respostas formatadas para a presença ou ausência de elementos `<fig>.`
- Adiciona docstrings detalhadas para a classe e seus métodos, fornecendo uma descrição clara de seus atributos e funcionalidades.
Por _commit_.
python3 -m unittest -v tests/sps/models/test_fig.py
python3 -m unittest -v tests/sps/validation/test_fig.py
NA
NA
TK #657 
NA
> Fix: fig validation

- packtools/sps/models/v2/article_xref.py
- packtools/sps/validation/article_xref.py
- tests/sps/models/v2/test_article_xref.py
- tests/sps/validation/test_article_xref.py
Este PR implementa uma série de classes (`Xref`, `Id`, `Xrefs`, `Ids`, `ArticleXref`) para facilitar a extração de referências (`xref`) e IDs de elementos em documentos XML de artigos científicos, incluindo suporte específico para sub-artigos de tradução. Com essas classes, é possível iterar sobre todos os IDs e referências de um artigo, identificando se eles pertencem ao artigo principal ou a sub-artigos, e se esses sub-artigos são traduções ou não. Além disso, este PR inclui um conjunto abrangente de testes unitários para validar a funcionalidade implementada.
A revisão pode começar pelos seguintes arquivos:
- `article_xref.py`
- `test_article_xref.py`
Para testar manualmente as funcionalidades deste PR:
1. Carregue um documento XML de artigo científico que contenha referências (xref) e …
> Fix: xref model

- packtools/sps/pid_provider/xml_sps_lib.py
Corrige a criação do elemento pub-date (pub) em XMLWithPre.
O defeito era que o pub-date estava sendo criado dentro de pub-date existente:
Incorreto
```xml
<pub-date date-type="collection" publication-format="electronic">
<month>04</month>
<year>2006</year>
<pub-date date-type="pub" publication-format="electronic"><day>06</day><month>09</month><year>2024</year></pub-date></pub-date>
```
correto:
```xml
<pub-date date-type="collection" publication-format="electronic">
<month>04</month>
<year>2006</year>
</pub-date>
<pub-date date-type="pub" publication-format="electronic">
<day>06</day><month>09</month><year>2024</year>
</pub-date>
```
por commits
Instanciando uma classe XMLWithPre um XML que não contém pub-date do tipo pub :
```python
for xml_with_pre in XMLWithPre.create(path=xml_path): …
```
> Corrige a criação do elemento pub-date (pub) em XMLWithPre

- packtools/sps/models/v2/article_toc_sections.py
- packtools/sps/validation/article_toc_sections.py
- packtools/sps/validation/exceptions.py
- tests/sps/models/test_article_toc_sections.py
- tests/sps/validation/test_article_toc_sections.py
Este PR adiciona uma nova funcionalidade de validação para garantir que cada idioma em um artigo contenha apenas um `subject` dentro das subseções (subj-group). Ele soluciona o problema de múltiplos `subjects` sendo associados ao mesmo idioma, o que não é permitido. A validação é implementada na função `validate_article_subsections`, que gera mensagens de erro detalhadas quando múltiplos `subject` são encontrados, oferecendo sugestões de como corrigir o formato.
Sugiro começar a leitura do código pelos seguintes arquivos e locais:
Arquivo de validação: Localize a função `validate_article_subsections` dentro do arquivo onde as validações do artigo são implementadas.
Arquivo de testes: Verifique o método `test_validate_article_toc_sections_more_then_one` no arquivo de testes para entender …
> Feat: subsection validation

- packtools/sps/models/v2/related_articles.py
- tests/sps/models/v2/test_related_articles.py
Este PR introduz um modelo para representar o elemento `<related-article>` em documentos XML. A implementação inclui classes que extraem e estruturam informações dos artigos relacionados, como `ext-link-type`, `related-article-type`, `id,` `href`, e o texto contido nas subtags. O objetivo é padronizar a forma como os dados de artigos relacionados são obtidos, facilitando a manipulação e utilização dessas informações em diferentes partes do sistema.
Por _commit_.
`python3 -m unittest -v tests/sps/models/v2/test_related_articles.py
`
NA
NA
NA
NA
> Related article model review

- packtools/sps/models/v2/notes.py
- tests/sps/models/v2/test_notes.py
Este PR implementa uma série de classes para o processamento de notas de artigos (`<fn>`, `<fn-group>`, `<author-notes>`) em documentos XML no formato SciELO PS. O objetivo é extrair, organizar e contextualizar essas notas em estruturas de dicionário que incluem informações detalhadas sobre o artigo, como tipo de artigo, idioma e identificadores. Esta implementação resolve o problema de extração manual e complexa de dados de notas, facilitando o uso programático dessas informações. Além disso, foram adicionados testes unitários abrangentes para validar o funcionamento correto de cada classe.
A revisão pode começar pelo arquivo `packtools/sps/models/v2/notes.py`, onde as classes `Fn`, `Fns`, `FnGroup`, `FnGroups`, `AuthorNote`, `AuthorNotes`, e `ArticleNotes` estão implementadas. Em …
> Refactor: article notes (fn-group / author-notes)

- packtools/sps/models/article_citations.py
- packtools/sps/validation/article_citations.py
- tests/sps/models/test_article_citations.py
- tests/sps/validation/test_article_citations.py
Este PR adiciona uma nova função de validação chamada `validate_article_citation_ext_link` que verifica se há exatamente um `<ext-link>` por referência em citações de artigos. A função é projetada para garantir que cada citação no elemento `<element-citation>` contenha um único link externo, evitando múltiplos links que possam causar confusão ou problemas de formatação.
Por _commit_.
Para testar manualmente a funcionalidade:
1. Insira ou modifique citações de artigos em um XML de teste para incluir diferentes quantidades de `<ext-link>`.
2. Execute a validação para verificar as respostas geradas.
3. Confirme que o sistema acusa um erro ("ERROR") se houver mais ou menos de um `<ext-link>` por citação de referência.
4. Valide se as mensagens geradas correspondem ao esperado, incluindo o …
> Feat: citation ext link validation

- packtools/sps/validation/article_doi.py
- tests/sps/validation/test_article_doi.py
Este PR adiciona uma nova validação para garantir que os DOIs de artigos e sub-artigos de tradução sejam distintos. A função `validate_different_doi_in_translation` verifica se o DOI do sub-artigo (tradução) é igual ao DOI do artigo principal e, caso sejam iguais, gera um aviso recomendando o uso de DOIs únicos para o artigo e o sub-artigo.
Por _commit_.
1. Utilize um XML de artigo que inclua DOIs para o artigo principal e para sub-artigos de tradução.
2. Assegure-se de que o DOI do artigo principal e do sub-artigo de tradução sejam iguais em alguns casos.
3. Execute a função `validate_different_doi_in_translation`.
4. Verifique que um aviso é gerado quando os DOIs do artigo e do sub-artigo de tradução são iguais, sugerindo o uso de DOIs distintos.
NA
NA
NA
NA
> Feat: different doi in translation validation

- packtools/sps/validation/article_author_notes.py
- tests/sps/validation/test_article_author_notes.py
Este PR adiciona duas funções de validação para garantir o uso correto de atributos de notas de autor e desencorajar práticas obsoletas:
- `validate_current_affiliation_attrib_type_deprecation`: Essa função valida o uso do atributo `fn-type="current-aff"` em notas de autor, que está obsoleto para indicar afiliações atuais. Ela gera uma resposta de validação com nível de erro "ERROR", sugerindo o uso da tag `<bio>` para dados de mini CV ou biografia do autor.
- `validate_contribution_attrib_type_deprecation`: Esta função verifica o atributo obsoleto `fn-type="con" `em notas de autor para contribuições de autoria. Caso encontrado, a validação sugere o uso da tag `<role>` em vez de `fn-type="con"`, gerando uma resposta de validação com nível de aviso "WARNING".
Por _commit_.
Avalie os teste …
> Feat: author notes validation

- packtools/sps/models/aff.py
- packtools/sps/validation/aff.py
- packtools/sps/validation/utils.py
- tests/sps/validation/test_aff.py
- Corrige valores da resposta da validação de aff: title, sub-item, advice etc.
- Refatora a resposta da validação
- Adiciona métodos para validar aff de article e aff de translation
por commits
```console
python -m unittest -v tests.sps.validation.test_aff
```
n/a
n/a
n/a
n/a
> Corrige valores da resposta da validação de aff: title, sub-item, advice etc

- packtools/sps/validation/aff.py
- tests/sps/validation/test_aff.py
- Adiciona error_level como parâmetros de AffiliationValidation.validate_main_affiliations e validate_translated_affiliations
- Também condiciona o retorno da resposta quando há erro ou quando o error_level é INFO
- Adiciona AffiliationValidation.validate_label
Por commits
```console
python -m unittest -v tests.sps.validation.test_aff
```
n/a
n/a
n/a
n/a
> Adiciona error_level como parâmetros de AffiliationValidation.validate_main_affiliations e validate_translated_affiliations

- packtools/sps/formats/sps_xml/article.py
- packtools/sps/formats/sps_xml/contrib.py
- packtools/sps/formats/sps_xml/journal_meta.py
- packtools/sps/models/v2/related_articles.py
- tests/sps/formats/sps_xml/test_article.py
- tests/sps/formats/sps_xml/test_contrib.py
- tests/sps/formats/sps_xml/test_journal_meta.py
- tests/sps/models/v2/test_related_articles.py
Este PR introduz três funções que geram estruturas XML usando a biblioteca `xml.etree.ElementTree`. Ele visa resolver a necessidade de criação dinâmica de elementos XML, tais como `<article>`, `<contrib>,` e `<journal-meta>`, com base em dados de entrada. 
A revisão pode começar pelos arquivos que contêm as seguintes funções:
- `build_article_node()` no arquivo `article.py`
- `build_contrib_author()` no arquivo `contrib.py`
- `build_journal_meta()` no arquivo `journal_meta.py`
1. Crie um script Python para importar as funções dos arquivos relevantes.
2. Forneça dados de entrada similares aos exemplos abaixo e execute as funções para gerar o XML.
Exemplo de dados para `build_article_node`:
```
article_data = {
"dtd-version": "1.1",
"specific-use": "research",
"article-type": "original", …
```
> Feat: build xml elements

- packtools/sps/models/article_abstract.py
Implementa codição if para ignorar abstracts do tipo gráfico em get_main_abstract e _get_sub_article_abstracts
pelos commits
N/A
N/A
#740 
N/A
> Implementa codição if para ignorar abstracts do tipo gráfico em get_main_abstract e _get_sub_article_abstracts

- packtools/sps/formats/sps_xml/disp_formula.py
- tests/sps/formats/sps_xml/test_disp_formula.py
Adiciona função para a criação do elemento `disp-formula` no formato xml.
Por _commit_.
`python3 -m unittest -v tests/sps/formats/sps_xml/test_disp_formula.py`
NA.
NA.
NA.
NA.
> Feat: build disp-formula element

- packtools/sps/formats/sps_xml/table_wrap.py
- tests/sps/formats/sps_xml/test_table_wrap.py
Adiciona função para gerar o elemento `table-wrap` no formato xml.
Por _commit_.
`python3 -m unittest -v tests/sps/formats/sps_xml/test_table_wrap.py
`
NA.
NA.
NA.
NA.
> Feat: build table wrap element

- packtools/sps/formats/sps_xml/front.py
- tests/sps/formats/sps_xml/test_front.py
Adiciona função para a criação do elemento `front`, no formato xml.
Por _commit_.
`python3 -m unittest -v tests/sps/formats/sps_xml/test_front.py`
NA.
NA.
NA.
NA.
> Feat: build front element

- packtools/sps/formats/sps_xml/fig.py
- tests/sps/formats/sps_xml/test_fig.py
Adiciona função para criar o elemento `fig` no formato xml.
Por _commit_.
Sugiro avaliar os testes.
NA.
NA.
NA.
NA.
> Feat: build fig element

- packtools/sps/formats/sps_xml/abstract.py
- tests/sps/formats/sps_xml/test_abstract.py
Adapta o módulo `abstract` para permitir a geração do elemento `trans-abstract`.
Por _commit_.
`python3 -m unittest -v tests/sps/formats/sps_xml/test_abstract.py`
NA.
NA.
NA.
NA.
> Feat: build trans abstract element

- packtools/sps/formats/sps_xml/funding_group.py
- tests/sps/formats/sps_xml/test_funding_group.py
Adiciona função para a criação do elemento `funding-group` no formato xml.
Por _commit_.
`python3 -m unittest -v tests/sps/formats/sps_xml/test_funding_group.py`
NA.
NA.
NA.
NA.
> Feat: build funding group element

- packtools/sps/formats/sps_xml/ack.py
- tests/sps/formats/sps_xml/test_ack.py
Adiciona função para a criação do elemento `ack`, no formato xml.
Por _commit_.
`python3 -m unittest -v tests/sps/formats/sps_xml/test_ack.py`
NA.
NA.
NA.
NA.
> Feat: build ack element

- packtools/sps/formats/sps_xml/ref_list.py
- tests/sps/formats/sps_xml/test_ref_list.py
Adiciona função para a criação do elemento `ref-list`, no formato xml.
Por _commit_.
Sugiro a avaliação dos testes:
`python3 -m unittest -v tests/sps/formats/sps_xml/test_ref_list.py`
NA.
NA.
NA.
NA.
> Feat: build ref list element

- packtools/sps/formats/sps_xml/back.py
- tests/sps/formats/sps_xml/test_back.py
Adiciona função para a criação do elemento `back`, no formato xml.
Por _commit_.
`python3 -m unittest -v tests/sps/formats/sps_xml/test_back.py
`
NA.
NA.
NA.
NA.
> Feat: build back element

- packtools/sps/formats/sps_xml/article.py
- tests/sps/formats/sps_xml/test_article.py
Complementa a função `build_article_node` para considerar os elementos filhos.
Por _commit_.
`python3 -m unittest -v tests/sps/formats/sps_xml/test_article.py`
NA.
NA.
NA.
NA.
> Feat: complements build article element

- packtools/sps/models/article_contribs.py
- tests/sps/models/test_article_contribs.py
Corrige contrib_name e teste de Contrib
pelos commits
```python 
python3 -m unittest tests.sps.models.test_article_contribs.ArticleContribTest
```
Artigo do error:
[article_teste.zip](https://github.com/user-attachments/files/18121691/article_teste.zip)
```console
INFO 2024-12-13 05:24:02,407 xmlsps 498560 138744031330432 load article article/fixtures/article_teste.xml None
ERROR 2024-12-13 05:24:02,702 models 498560 138744031330432 sequence item 3: expected str instance, NoneType found
Traceback (most recent call last):
File "/home/samuelv/Desktop/scielo/core/core/article/sources/xmlsps.py", line 96, in load_article
create_or_update_researchers(xmltree=xmltree, user=user, item=pid_v3)
File "/home/samuelv/Desktop/scielo/core/core/article/sources/xmlsps.py", line 341, in …
```
> Corrige contrib_name

- packtools/sps/models/article_and_subarticles.py
- packtools/sps/models/article_titles.py
- packtools/sps/models/v2/related_articles.py
- packtools/sps/validation/article_lang.py
- tests/sps/models/test_article_and_subarticles.py
- tests/sps/models/v2/test_related_articles.py
- tests/sps/validation/test_article_lang.py
Altera a iteração sobre os títulos para o artigo e sub-artigos.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_lang.py
`
NA
NA
TK #712 
NA.
> Fix: article lang validation

- packtools/sps/models/v2/aff.py
- packtools/sps/validation/aff.py
- packtools/sps/validation/exceptions.py
- packtools/sps/validation/xml_validations.py
- tests/sps/validation/test_aff.py
Revisa as validações de aff
- melhoria em nomes de classes, métodos, exceções
- passa a considerar obrigatório country_code_list como parâmetro de `__init__`, que seria mais fácil do que completar como parâmetro em vários métodos onde estava ausente
- elimina os métodos que validate e validate_affiliation_list por suprimir os parâmetros dos métodos chamados, sendo úteis somente se fossem ser usados com  os valores default dos métodos chamados. Sendo assim, melhor chamar diretamente os métodos.
- corrige o método que verifica a quantidade de aff em article-meta e sub-articles. Há 3 testes e todos testam a mesma situação de que os valores estão corretos. **É necessário adicionar testes para artigos que contém **mais de um** sub-article e testes para quando somente há article sem …
> Modifica packtools.sps.models.v2.aff e modifica validações de afiliações 

- packtools/sps/validation/article_abstract.py
- packtools/sps/validation/xml_validations.py
- packtools/sps/validation_rules/abstract_rules.json
- packtools/sps/validation_rules/graphical_abstract_rules.json
- packtools/sps/validation_rules/highlight_rules.json
- tests/sps/validation/test_article_abstract.py
Modifica e acrescenta a validação de existência dos resumos condicionando ao article-type, por exemplo, não é esperado que em editorial exista resumo.
por commits
```console
python -m unittest -v  tests.sps.validation.test_article_abstract
```
n/a
n/a
n/a
n/a
> Modifica e acrescenta a validação de existência dos resumos condicionando ao article-type

- packtools/sps/validation/article_and_subarticles.py
- packtools/sps/validation/utils.py
Faz melhorias em packtools.sps.validation.article_and_subarticles
por commits
```console
python -m unittest -v tests.sps.validation.test_article_and_subarticles
```
Pendente adequar os testes às mudanças
n/a
n/a
n/a
> Faz melhorias em packtools.sps.validation.article_and_subarticles

- packtools/sps/utils/xml_utils.py
- packtools/sps/validation/article_contribs.py
- packtools/sps/validation/xml_validations.py
- packtools/sps/validation_rules/article_contribs_rules.json
- tests/sps/validation/test_article_contribs.py
Revisa as validações quanto aos autores
- adiciona validação de existência de name ou collab
- corrige a validação de collab-list
por commtis
```python
python -m unittest -v tests.sps.validation.test_article_contribs
```
n/a
n/a
n/a
n/a
> Adiciona validação de existência de name ou collab e corrige a validação de collab-list

- packtools/sps/validation/fig.py
- packtools/sps/validation_rules/article_type_rules.json
- packtools/sps/validation_rules/fig_rules.json
Cria validação individual das figuras e cria validação de todas as figuras do artigo
por commts
pendente de criar os testes automáticos
- pendente de fazer o mesmo para table-wrap e disp-formula
n/a
n/a
n/a
> Cria validação individual das figuras e cria validação de todas as figuras do artigo

- tests/sps/validation/test_article_and_subarticles.py
Adapta os testes às modificações implementadas para o módulo de validação de `article and sub-article`.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_and_subarticles.py`
NA.
NA.
TK #792 
NA.
> Fix: article and sub-article tests

- tests/sps/validation/test_article_contribs.py
Adapta os testes de acordo com as melhorias implementadas.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_contribs.py`
NA.
NA.
TK #795 
NA.
> Fix: article contribs validation tests

- packtools/sps/validation/article_toc_sections.py
- tests/sps/validation/test_article_toc_sections.py
Corrige os testes das validações de `article toc sections`.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_toc_sections.py`
NA.
NA.
TK #798 
NA.
> Fix: article toc sections validation tests

- tests/sps/models/test_article_assets.py
- tests/sps/models/test_article_authors.py
- tests/sps/models/test_article_dates.py
- tests/sps/models/test_article_ids.py
- tests/sps/models/test_article_titles.py
- tests/sps/models/test_sps_maker.py
- tests/sps/models/v2/test_aff.py
- tests/sps/models/v2/test_article_xref.py
Adiciona skip para que os testes dos modelos que estão quebrados não afetem a execução.
NA.
NA.
NA.
NA.
NA.
NA.
> Chore: skip problematic tests to prevent execution failures in models

- packtools/sps/models/funding_group.py
- packtools/sps/validation/funding_group.py
- packtools/sps/validation/xml_validations.py
- packtools/sps/validation_rules/funding_data_rules.json
- tests/sps/models/test_funding_group.py
- tests/sps/validation/test_funding_group.py
Corrige a validação de dados de financiamento: É obrigatório haver award-id se há "números" em ack, funding-statement, fn. É comum que os produtores de XML, não identifiquem apropriadamente award-id, por haver uma variedade de elementos para identificar financiamento. No entanto, os dados mais relevantes é o de número de contrato que prova que a pesquisa teve um financiamento. 
por commits
```console
python -m unittest -v  tests/sps/models/test_funding_group.py
```
```console
python -m unittest -v  tests/sps/validation/test_funding_group.py
```
n/a
n/a
n/a
n/a
> Corrige a validação de dados de financiamento

- packtools/sps/models/related_articles.py
- packtools/sps/utils/xml_utils.py
- tests/sps/models/test_related_articles.py
Adiciona text e xml dos itens retornados por RelatedItems.related_articles
por commits
```console
python -m unittest -v  tests/sps/models/test_related_articles.py
```
n/a
n/a
n/a
n/a
> Adiciona text e xml dos itens retornados por RelatedItems.related_articles

- packtools/sps/models/related_articles.py
- packtools/sps/validation/related_articles.py
- packtools/sps/validation/utils.py
- packtools/sps/validation/xml_validations.py
- packtools/sps/validation/xml_validator.py
- packtools/sps/validation_rules/related_article_rules.json
- tests/sps/models/test_related_articles.py
- tests/sps/validation/test_related_articles.py
Reescreve as validações de related-article, para considerar a necessidade de agrupar os related-article por article e sub-article, pois para alguns `@article-type` há um `relate-article` com `@related-article-type` obrigatório, por exemplo, 'correction' e 'corrected-article'. 
O modelo RelatedItems não atendia a demanda. Foi mantido, mas foi criado Fulltext.
Foi necessário criar:
- FulltextValidation para contextualizar as validações de article e sub-article.
- RelatedArticleValidation para validações individuais
- Reescrever RelatedArticlesValidation que passou a usar FulltextValidation
por commits
```console
python -m unittest -v  tests/sps/models/test_related_articles.py
```
```console
python -m unittest -v  tests/sps/validation/test_related_articles.py
```
n/a
n/a
n/a
n/a
> Reescreve as validações de related-article

- packtools/sps/validation/basefn.py
Adiciona módulo com validações genéricas para `fn`, os testes são implementados nas classes que herdam `basefn`.
NA.
NA.
NA.
NA.
NA.
NA.
> Refactor: basefn validations

- packtools/sps/validation/aff.py
Ajusta o conteúdo de `advice` nas funções de validação de `aff`.
Por _commit_.
NA.
NA.
NA.
TK #878 
NA.
> Fix: aff advice

- packtools/sps/validation/journal_meta.py
Ajusta o conteúdo de `advice` nas funções de validação de `journal-meta`.
Por _commit_.
NA.
NA.
NA.
TK #878 
NA.
> Fix: journal-meta advice

- packtools/sps/validation/aff.py
- tests/sps/validation/test_aff.py
Valida se os componentes de `aff` estão presentes no `original` e se todas as palavras em `original` estão em algum sub-elemento (componente) de `aff`, com destaque para as palavras que não entraram em nenhum sub-elemento.
Por _commit_.
Avaliar os testes.
NA.
NA.
TK #896 
NA.
> Feat validate original components

- packtools/data_checker.py
- packtools/sps/validation/xml_validator.py
Melhora o utilitário de validação:
- modifica os parâmetros
- permite criar um csv por xml  ou criar um csv para todos os xmls
por commits
1. Validando apenas 1 xml, criando csv junto ao xml
```console
python packtools/data_checker.py /path/2175-9146-jatm-16-e21243.xml diretorio_de_saida --csv_per_xml
```
No `diretorio_de_saida`, será gerado um arquivo de exceções, se acontecer.
2. Validando apenas 1 xml, criando csv no diretorio_de_saida
```console
python packtools/data_checker.py /path/2175-9146-jatm-16-e21243.xml diretorio_de_saida
```
3. Validando vários xmls, criando csv junto ao xml
```console
python packtools/data_checker.py /path/xmls diretorio_de_saida --csv_per_xml
```
Sendo:
- `/path/xmls` - pasta com os xmls, o sistema percorrerá daí para baixo, obterá todos os xmls
- …
> Melhora o utilitário de validação

- packtools/catalogs/htmlgenerator/v3.0/article.xsl
- packtools/catalogs/htmlgenerator/v3.0/bottom-floating-menu.xsl
> Troca o html do menu flutante do rodapé

- tests/sps/models/v2/test_article_xref.py
Corrige e atualiza os testes do módulo `article_xref` para refletir corretamente a lógica atual de extração de elementos com `id` e referências cruzadas (`xref`) em XML JATS. Ajusta testes quebrados, métodos inexistentes e validações incorretas.
`tests/sps/models/v2/test_article_xref.py`
`python3 -m unittest -v tests/sps/models/v2/test_article_xref.py`
NA
NA
NA
NA
> Adapta os testes às correções implementadas para o modelo de article-xref

- tests/sps/models/test_article_contribs.py
Refatora e organiza os testes do módulo `article_contribs`, com foco nas classes `Contrib`, `TextContribs` e `XMLContribs`.
Foram removidos decorators `@skip`, centralizado o XML de teste, reduzida duplicação e reestruturada a escrita dos testes para melhorar legibilidade e manutenção.
Também foram incluídos testes para `sub-article` e para mapeamento de nomes por ORCID.
Arquivo:
`tests/sps/models/test_article_contribs.py`
Comece pela classe `ContribTest` e siga pelas demais (`TextContribsTest`, `XMLContribsTest`).
`python3 -m unittest -v tests/sps/models/test_article_contribs.py`
NA
NA
NA
NA
> Adapta os testes às correções implementadas para o modelo de article-contribs

- packtools/sps/models/visual_resource_base.py
- tests/sps/models/test_visual_resource_base.py
Adiciona modelo VisualResourceBase e testes.
Por _commit_.
NA
NA
NA
Substitui PR #915 
NA
> Adiciona modelo VisualResourceBase e testes

- tests/sps/models/test_article_authors.py
Remove `skip` dos testes para `article-authors` e complementa o dicionário.
NA
NA
NA
NA
NA
NA
> Corrige os testes para 'article_authors'

- packtools/sps/models/accessibility_data.py
- packtools/sps/models/supplementary_material.py
- packtools/sps/validation/supplementary_material.py
- packtools/sps/validation_rules/supplementary_material_rules.json
- packtools/sps/validation_rules/visual_resource_base_rules.json
- tests/sps/validation/test_supplementary_material.py
Corrige validação para `SupplementaryMaterial` e testes.
NA
NA
NA
NA
NA
> Corrige validação para SupplementaryMaterial e testes

- packtools/sps/models/article_authors.py
Este PR marca o módulo `article_authors` como obsoleto e o substitui por `article_contribs`.
NA
NA
NA
NA
NA
NA
> Deprecate article_authors in favor of article_contribs

- packtools/sps/formats/am/am.py
- packtools/sps/formats/am/am_utils.py
- packtools/sps/formats/am/generate_am.py
- packtools/sps/models/article_abstract.py
- packtools/sps/models/funding_group.py
- tests/sps/formats/am/test_am.py
- tests/sps/models/test_funding_group.py
Este PR atualiza o script generate_am.py para permitir a geração de arquivos .am.json a partir de:
- Um único arquivo XML ou
- Um diretório com múltiplas subpastas, processando apenas as pastas folha (sem subpastas internas).
Além disso:
- Suporta opcionalmente dois arquivos JSON externos (external_article_data.json e external_citation_data.json);
- Gera o .am.json na mesma pasta do XML de origem;
- Registra erros em um arquivo generate_am.log sem interromper o processamento dos demais arquivos.
Por _commit_.
`python script.py /caminho/para/artigo.xml`
`python script.py /caminho/para/colecao/`
`python script.py /caminho/artigo.xml dados_article.json`
`python script.py /caminho/artigo.xml dados_article.json dados_citation.json`
`python script.py /caminho/colecao/ dados_article.json …
> Fix: generate_am

- packtools/catalogs/htmlgenerator/v2.0/article-text-back.xsl
- packtools/catalogs/htmlgenerator/v3.0/article-text-supplementary-material.xsl
- packtools/catalogs/htmlgenerator/v3.0/article-text-xref.xsl
- packtools/catalogs/htmlgenerator/v3.0/generic.xsl
Implementa navegação por âncoras internas para melhorar a experiência de leitura de artigos científicos:
- Adiciona IDs em elementos estruturais (seções back, material suplementar)
- Transforma referências cruzadas (xref) em links clicáveis que navegam até o elemento referenciado
- Corrige estrutura de material suplementar envolvendo links em parágrafos identificados
`packtools/catalogs/htmlgenerator/v3.0/generic.xsl` - contém o template base que gera spans com ID, fundamental para entender o sistema.
1. Gere HTML de artigo com: seções back matter, referências cruzadas (xref) e material suplementar
2. Verifique no HTML gerado:
- Elementos com `@id` possuem `<span id="..."/>`
- Cliques em xref navegam para elemento referenciado
- Links de material suplementar estão em `<p name="id">`
3. …
> feat: Implementa sistema de navegação por âncoras internas em artigos HTML para material suplementar

- packtools/sps/utils/prepare_request_data.py
- tests/sps/utils/test_prepare_request_data.py
Adiciona funcionalidade para extrair e transformar dados de artigos XML (formato SciELO SPS) em payloads compatíveis com APIs externas, especificamente para integração com ORCID. A função `prepare_request_data` processa metadados de autores (ORCID, nome, email) e trabalhos acadêmicos (título, journal, DOI, datas de publicação) com validações rigorosas para garantir qualidade dos dados.
Inicie pela leitura do arquivo `packtools/sps/utils/prepare_request_data.py` que contém a implementação principal com as classes `Author`, `Authors` e `Work`. Em seguida, examine `test_prepare_request_data.py` para entender os casos de uso e validações implementadas.
1. Prepare um arquivo XML no formato SciELO SPS com contribuidores que possuam ORCID e nome completo
2. Execute o código:
```
from lxml import …
```
> Feat: add prepare_request_data for ORCID API integration

- packtools/catalogs/htmlgenerator/v3.0/article-text-supplementary-material.xsl
Corrige apresentação de material suplementar
```xml
<back>
<sec>
--
<supplementary-material id="suppl02" mime-subtype="pdf" mimetype="application" orientation="portrait" position="float" xlink:href="https://minio.scielo.br/documentstore/2318-0331/4nz5gmtGxgDrPFMFyLYYdMn/b4ced55f07aba9a7ee82f9f7b77107476ec45dae.pdf">
--
<label>Figure A. 1 –</label>
<caption>
<title>Accumulated daily rainfall anomalies for the climatological year of 2004, highlighting the beginning and end of the rainy season.</title>
</caption>
</supplementary-material>
<supplementary-material id="suppl2">
<label>Supplementary Material II</label>
<media mimetype="application" mime-subtype="pdf"
xlink:href="1980-5764-dn-19-s1-e20240251-suppl02.pdf"/>
</supplementary-material>
</sec>
<app-group>
<app id="app01"> …
```
> Corrige apresentação de material suplementar
