- MANIFEST.in
- packtools/catalogs/default-html.xslt
- packtools/domain.py
- packtools/htmlgenerator.py
- packtools/stylechecker.py
- tests/test_htmlgenerator.py
Adicionar tests para o resultado da transformação XSLT
- o arquivo com os tests: ``/tests/test_htmlgenerator.py``
- o arquivo da XSLT: ``/packtools/catalogs/default-html.xslt``
``python setup.py test -s tests.test_htmlgenerator``
> ajustes e novos tests para testar o resultado da transformação

- packtools/catalogs/default-html.xslt
- tests/test_htmlgenerator.py
Adicionar tests para o resultado da transformação XSLT
- o arquivo com os tests: ``/tests/test_htmlgenerator.py``
- o arquivo da XSLT: ``/packtools/catalogs/default-html.xslt``
``python setup.py test -s tests.test_htmlgenerator.GeneratedTagsTests``
> novos tests para testar o resultado da transformação

- packtools/catalogs/__init__.py
- packtools/catalogs/scielo-style-1.5.sch
- tests/test_schematron_1_5.py
Esse pull-request vai atender a todas as alterações descritas no ticket #94.
> Adiciona suporte à SciELO PS 1.5.

- packtools/catalogs/scielo-style-1.5.sch
- tests/test_schematron_1_5.py
> Valida a presença de atributos e seus valores para o elemento *related-article*. 

- packtools/catalogs/scielo-style-1.3.sch
- packtools/catalogs/scielo-style-1.4.sch
- packtools/catalogs/scielo-style-1.5.sch
> Remove expressão XPath responsável por erros de compilação.

- HISTORY.rst
- tests/test_schematron_1_1.py
- tests/test_schematron_1_2.py
- tests/test_schematron_1_3.py
- tests/test_schematron_1_4.py
- tests/test_schematron_1_5.py
- tests/test_scielo_br.py
> Avoid copying instances of Schematron.

- HISTORY.rst
- packtools/catalogs/scielo-publishing-schema.xml
- scripts/install_xml_catalog.sh
> Causes the XML catalog to resolve system ids of type URL.

- HISTORY.rst
- packtools/stylechecker.py
> The stylechecker utility exits 0 on success, and >0 if an error occurs

- HISTORY.rst
- packtools/catalogs/scielo-style-1.5.sch
- packtools/catalogs/scielo-style-1.6.sch
> Fixes a bug that would cause element's text to be printed out instead of element's name.

- HISTORY.rst
- packtools/domain.py
- packtools/style_errors.py
- packtools/stylechecker.py
> Make it possible to know which Validator originated which error messages.

- HISTORY.rst
- packtools/utils.py
> Schematron schema parser tunning.

- packtools/catalogs/__init__.py
- packtools/catalogs/checks.py
- packtools/domain.py
- packtools/htmlgenerator.py
- packtools/stylechecker.py
- packtools/utils.py
- tests/test_schematron_1_1.py
- tests/test_schematron_1_2.py
- tests/test_schematron_1_3.py
- tests/test_schematron_1_5.py
- tests/test_schematron_1_6.py
- tests/test_schematron_1_7.py
- tests/test_schematron_1_8.py
- tests/test_scielo_br.py
This fix uses a hack that ovewrites the catalogs package dynamically at
import/load time. See catalogs/__init__.py last lines for more info.
> Fixes the api of the package catalogs.

- .gitignore
- packtools/webapp/static/css/codemirror/lib/codemirror.css
- packtools/webapp/static/js/codemirror/lib/codemirror.js
Adição dos arquivos staticos do codemirror que estavao na pasta `lib` devido ao `.gitignore`
* `.gitignore` 
* `packtools/webapp/static/css/codemirror/lib/codemirror.css`
*  `packtools/webapp/static/js/codemirror/js/codemirror.css`
Apos atualizar o codigo, rodar o server do Flask e ver se o codemirror é carregado
#176
#192
> Adição de arquivos staticos do codemirror scieloorg/packtools#176

- HISTORY.md
> Atualiza HISTORY

- HISTORY.md
- packtools/version.py
- tests/test_xmlvalidator.py
Corrige os testes relacionados com a criação do comentário SPS-ERROR
#255
> Corrige os testes relacionados com a criação do comentário SPS-ERROR

- packtools/catalogs/htmlgenerator/v2.0/article.xsl
- packtools/catalogs/htmlgenerator/v2.0/config-vars.xsl
- packtools/domain.py
- packtools/htmlgenerator.py
Gera um HTML alternativo, para uso do website
por commits
Executando o htmlgenerator ou instanciando o HTMLGenerator
**Saída para o site**
```console
python packtools/htmlgenerator.py --loglevel DEBUG --nonetwork --nochecks <xml> --output_style website
```
**Saída padrão**
```console
python packtools/htmlgenerator.py --loglevel DEBUG --nonetwork --nochecks <xml>
```
n/a
n/a
#258
n/a
> Gera um HTML alternativo, para uso do website

- packtools/catalogs/htmlgenerator/v2.0/article-text-fig.xsl
- packtools/catalogs/htmlgenerator/v2.0/article-text-graphic.xsl
- tests/test_htmlgenerator.py
Adiciona um link envolvendo as tags images na página do artigo.
Por commit e pelos testes unitários.
Com uma instância do opac com uma nova versão do packtools.
N/A
N/A
N/A
N/A
> Adiciona um link envolvendo as tags images na página do artigo.

- packtools/catalogs/htmlgenerator/v2.0/article-meta-contrib.xsl
- packtools/catalogs/htmlgenerator/v2.0/config-labels.xml
- packtools/catalogs/htmlgenerator/v2.0/html-modals-contribs.xsl
- tests/fixtures/htmlgenerator/translator/dqR6y8bPFVVQnxnFHY66ZZK.pt.html
- tests/fixtures/htmlgenerator/translator/dqR6y8bPFVVQnxnFHY66ZZK.xml
Explicita a contribuição de tradução no modal e remove o tradutor da lista de autores
por commits
executando
```console
python packtools/htmlgenerator.py --nochecks --nonetwork --loglevel DEBUG tests/fixtures/htmlgenerator/translator/dqR6y8bPFVVQnxnFHY66ZZK.xml
```
n/a
n/a
https://github.com/scieloorg/opac/issues/2321
n/a
> Explicita a contribuição de tradução

- packtools/sps/models/front_journal_meta.py
- tests/sps/test_front_journal_meta.py
Cria classe para facilitar o acesso a dados de ISSN do periódico do artigo
por commits
```console
python -m unittest -v tests.sps.test_front_journal_meta
```
n/a
n/a
n/a
n/a
> Cria classe para facilitar o acesso a dados de ISSN do periódico do artigo

- packtools/sps/models/article_doi_with_lang.py
- tests/sps/test_article_doi_with_lang.py
Cria a classe DoiWithLang para acessar os dados de DOI do XML
por commits
Com os testes automatizados ou instanciando a classe
n/a
n/a
n/a
n/a
> Cria a classe DoiWithLang para acessar os dados de DOI do XML

- packtools/sps/models/article_authors.py
- tests/sps/test_article_authors.py
Cria classe para acessar os dados de autoria do artigo
por commits
```console
python -m unittest -v tests.sps.test_front_authors
```
n/a
n/a
n/a
n/a
> Cria classe para acessar os dados de autoria do artigo

- packtools/sps/models/body.py
- tests/sps/test_body.py
Classe para acessar os textos do body do XML
por commits
executando os testes automatizados ou instanciando a classe
n/a
n/a
n/a
n/a
> Classe para acessar os textos do body do XML

- packtools/file_utils.py
- packtools/file_utils_mimetype.py
- packtools/sps/models/article_titles.py
- packtools/sps/sps_maker.py
- packtools/sps/utils/xml_utils.py
- tests/sps/test_article_titles.py
- tests/sps/test_xml_utils.py
Cria classe para acessar títulos de artigos do XML
por commits
```console
python -m unittest -v tests.sps.test_article_titles
```
n/a
n/a
n/a
n/a
> Cria classe para acessar títulos de artigos do XML

- packtools/sps/models/article_ids.py
> Corrige setter de ArticleIds.aop_pid

- packtools/sps/models/article_assets.py
- packtools/version.py
- tests/sps/fixtures/document-with-supplementary-material.xml
- tests/sps/test_article_assets.py
Adiciona modelo ArticleAssets para obter uma lista de objetos Asset.
O objeto Asset, tendo um ID, pode ser organizado em um dicionário, como fazem os testes.
Por commits.
É possível fazer algo como o seguinte para ver os dados de cada Asset (estando em um venv do projeto):
```python
from packtools.sps.models.article_assets import ArticleAssets
from packtools.sps.utils import xml_utils
filepath = '/home/user/meuarquivo.xml' # Altere para o caminho do arquivo XML a ser testado
with open(filepath) as fin:
xmltree = xml_utils.get_xml_tree(fin.read())
aa = ArticleAssets(xmltree)
for i in aa.article_assets:
print(i.id, i.name, i.node)
```
Seguem exemplos de retorno das insturções acima, a depender do XML informado:
```
f01 2318-0889-tinf-33-e200071-gf01.tif <Element graphic at 0x7f20bcb5a800> …
```
> Adiciona modelos e testes para ArticleAssets e Asset

- packtools/sps/models/related_articles.py
- tests/sps/test_related_articles.py
Cria classe para obter do XML os dados de `related-article`
por comits
Veja os testes automatizados
n/a
n/a
n/a
n/a
> Cria classe para obter do XML os dados de `related-article`

- packtools/sps/models/article_assets.py
- tests/sps/test_article_assets.py
Cria classe para extrair do XML os materiais suplementares  e cria ArticleAssets.replace_names
por commits
Veja os testes
n/a
n/a
n/a
n/a
> Cria classe para extrair do XML os materiais suplementares e cria ArticleAssets.replace_names

- packtools/sps/models/article_and_subarticles.py
- tests/sps/test_article_and_subarticles.py
Adiciona classe ArticleAndSubarticles para obter idioma e tipo de artigo (e todos os subartigos)
Por commits.
N/A
N/A
N/A
N/A
N/A
> Adiciona classe que identifica dados principais de article e subarticle

- packtools/catalogs/htmlgenerator/v2.0/article-meta-related-article.xsl
- packtools/version.py
- tests/fixtures/htmlgenerator/related-article/varias_erratas.en.html
- tests/fixtures/htmlgenerator/related-article/varias_erratas.pt.html
- tests/fixtures/htmlgenerator/related-article/varias_erratas.xml
Remove duplicação de texto (`Esta errata corrige:`)
por commits
```console
htmlgenerator --nonetwork --nochecks --loglevel DEBUG  tests/fixtures/htmlgenerator/related-article/varias_erratas.xml
```
n/a
n/a
n/a
n/a
> Remove duplicação de texto (`Esta errata corrige:`)

- packtools/catalogs/htmlgenerator/v2.0/article-text-section-data-availability.xsl
- packtools/version.py
Inclui um bloco de Dados de Pesquisa junto com o texto de material suplementar
por commits
```console
htmlgenerator --nonetwork --nochecks --loglevel DEBUG  tests/fixtures/htmlgenerator/data-availability/hxcB3n9hzmSGz4v6dgzDsxp.xml
```
n/a
#2506
comentários no issue
> Inclui um bloco de Dados de Pesquisa junto com o texto de material suplementar

- packtools/sps/models/dates.py
- packtools/sps/validation/dates.py
- packtools/sps/validation/values.py
- tests/sps/validation/test_dates.py
Adiciona funções para a validação da completude de data e da ordenação de datas em `history`.
Por _commit_.
A partir dos casos de testes automatizados.
NA.
NA.
TK #365 e #366.
NA.
> Validation date

- packtools/sps/validation/front_articlemeta_issue.py
- tests/sps/validation/test_front_articlemeta_issue.py
Adiciona classes para validação de atributos de `issue` (`volume`, `issue` e `supplement`) com os respectivos testes automatizados.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_front_articlemeta_issue.py`
NA.
NA.
TK #374.
[SciELO Publishing Schema](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/1.9-branch/tagset/elemento-issue.html#exemplo-1-suplemento-de-numero)
> Validation issue

- .gitignore
adicionado venv ao gitignore
Pelo .gitignore
Relizando o push e verificando que o .venv está incluido no gitignore
N/A
N/A
N/A
N/A
> adicionado venv ao gitignore

- packtools/sps/models/aff.py
- tests/sps/test_aff.py
Cria classe de extração e teste relacionados ao dados de afiliação 
Pelo commit.
`python setup.py test -s tests/sps/test_aff.py`
N/A
N/A
[#382](https://github.com/scieloorg/packtools/issues/382)
N/A
> Cria classe de extracao e teste relacionados aos dados de afiliacao

- packtools/sps/validation/aff.py
- tests/sps/validation/test_aff.py
Adiciona validação para affiliation 
Pelo commit
`python setup.py test -s tests/sps/validation/test_aff.py `
N/A
N/A
[#399](https://github.com/scieloorg/packtools/issues/339)
N/A
> Validacao para affiliation criada

- packtools/catalogs/htmlgenerator/v2.0/article-meta-permissions.xsl
- tests/fixtures/htmlgenerator/dot_in_id/arquivo.pt.3_0.html
- tests/fixtures/htmlgenerator/dot_in_id/arquivo.pt.html
- tests/fixtures/htmlgenerator/dot_in_id/tabelas.pt.3_0.html
- tests/fixtures/htmlgenerator/dot_in_id/tabelas.pt.html
Corrige o link da imagem da licença de uso. 
Corrige o termo `deed` (estava `deen`) para ser extraído da URI de licença e formar o link para a imagem
por commits
```console
python packtools/htmlgenerator.py --css /Users/roberta.takenaka/github.com/scieloorg/packtools/packtools/catalogs/htmlgenerator/static/scielo-article-standalone.css --print_css /Users/roberta.takenaka/github.com/scieloorg/packtools/packtools/catalogs/htmlgenerator/static/scielo-bundle-print.css --js /Users/roberta.takenaka/github.com/scieloorg/packtools/packtools/catalogs/htmlgenerator/static/scielo-article-standalone-min.js --nonetwork --nochecks --loglevel DEBUG  tests/fixtures/htmlgenerator/dot_in_id/tabelas.xml
```
```console
python packtools/htmlgenerator.py --css …
```
> Corrige o link da imagem da licença de uso

- packtools/sps/formats/pubmed.py
- tests/sps/formats/test_pubmed.py
Adiciona funções para tratar arquivos XML no padrão SciELO e representa-los em arquvos XML no padrão PudMed.
Por commit.
Avaliar os testes.
NA.
NA.
TK #417 
NA.
> Pubmed format

- packtools/sps/models/article_citations.py
- tests/sps/test_article_citations.py
Refatora os métodos de extração de dados de citações (referências).
Por commit.
A partir da avaliação dos testes.
NA.
NA.
TK #422 
NA.
> Article ref list

- packtools/sps/models/article_citations.py
- tests/sps/test_article_citations.py
Adiciona os atributos `<prefix>` e `<suffix>` ao modelo `ArticleCitations`
Por _commit_
Avaliar os testes.
NA.
NA.
TK #422 
[https://jats.nlm.nih.gov/publishing/tag-library/1.3/chapter/tag-names.html#pub-tag-names-cites](url)
> Adiciona atributos

- packtools/catalogs/htmlgenerator/v2.0/html-modals-contribs.xsl
- tests/fixtures/htmlgenerator/scimago/funciona.xml
- tests/fixtures/htmlgenerator/scimago/nao-funciona.en.html
- tests/fixtures/htmlgenerator/scimago/nao-funciona.xml
Apresenta as instituições representadas no XML em contrib-group/aff.
por commits
Executando
```console
python packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG tests/fixtures/htmlgenerator/scimago/nao-funciona.xml
```
n/a
n/a
#438 
n/a
> Version python27 fix scimago modal

- packtools/sps/libs/requester.py
- requirements.txt
Adiciona módulo que realiza requisições com tentativas
> Adiciona módulo que realiza requisições com tentativas

- packtools/sps/pid_provider/v3_gen.py
- packtools/sps/pid_provider/xml_sps_adapter.py
- packtools/sps/pid_provider/xml_sps_lib.py
- tests/sps/pid_provider/test_xml_sps_adapter.py
- tests/sps/pid_provider/test_xmlsps.py
Cria um módulo pid_provider para ser usado como biblioteca em core e upload
> Cria um módulo pid_provider para ser usado como biblioteca em core e upload

- packtools/sps/pid_provider/xml_sps_lib.py
Adiciona a exceção ValueError que é lançada quando tenta converter str em int
> Adiciona a exceção ValueError que é lançada quando tenta converter str em int

- packtools/sps/pid_provider/xml_sps_lib.py
Pid provider fix exceptions e adiciona o arquivo __init__.py
> Pid provider fix exceptions e adiciona o arquivo __init__.py

- packtools/sps/pid_provider/xml_sps_lib.py
> Fix get xml with pre from uri

- packtools/sps/models/article_authors.py
Corrige ausência de "contrib-type"
> Corrige ausência de "contrib-type"

- packtools/sps/models/article_assets.py
- packtools/sps/models/article_authors.py
Corrige atribuição de variável do tipo nó para evitar aviso de "The behavior of this method will change in future versions"
> Corrige atribuição de variável do tipo nó para evitar aviso de "The behavior of this method will change in future versions"

- packtools/sps/formats/crossref.py
Adapta e corrige funções de acordo com as mudanças na obtenção de informações sobre afiliações.
Por _commit_.
Os testes podem ser executados com o seguinte comendo:
`python3 -m unittest -v tests/sps/formats/test_crossref.py`
As adaptações são necessárias para a sequência dos processos de geração de arquivo XML.
NA.
NA.
NA.
> Adapta obtenção de afiliações

- packtools/sps/models/funding_group.py
- tests/sps/models/test_funding_group.py
Adequar a classe `funding_group`
Por _commit_
Avaliar os testes
NA.
NA.
NA.
NA.
> Completa classe funding

- packtools/catalogs/htmlgenerator/v2.0/article-text-list.xsl
- packtools/sps/models/article_authors.py
Corrige apresentação de lista do tipo "simple"
Por commits
Tenha um XML contendo:
```xml
<list list-type="simple">
<list-item>
<p>2.1. FALTA DE VISÃO SOBRE HIERARQUIA DE FONTES PARA PESQUISA.</p>
</list-item>
<list-item>
<p>2.2. HEGEMONIA DA DOUTRINA E ABUSO DE CITAÇÕES DE MANUAL.</p>
</list-item>
<list-item>
<p>2.3. USO ADVOCATÍCIO DAS FONTES (ESPECIALMENTE JULGADOS): CITAÇÃO DE JULGADOS QUE CONFIRMAM UMA TESE, SEM PESQUISA SISTEMÁTICA DE JURISPRUDÊNCIA QUE MOSTRE SUA RELEVÂNCIA E REPRESENTATIVIDADE.</p>
</list-item>
<list-item>
<p>2.4. MAU USO DO DIREITO COMPARADO: COMPARAÇÃO SEM MÉTODO E FORA DE CONTEXTO.</p>
</list-item>
</list>
```
Execute o htmlgenerator
```console
python packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG  lista_simple.xml
```
n/a
antes
depois
... …
> [página do artigo] Corrige apresentação de lista do tipo "simple"

- packtools/sps/models/article_citations.py
- tests/sps/models/test_article_citations.py
Complementa informações sobre citações.
Por _commit_.
Por meio da avaliação dos testes:
`python3 -m unittest -v tests/sps/models/test_article_citations.py`
NA.
NA.
TK #475.
https://jats.nlm.nih.gov/archiving/tag-library/1.3/element/ref-list.html
https://jats.nlm.nih.gov/archiving/tag-library/1.3/element/elocation-id.html
https://jats.nlm.nih.gov/archiving/tag-library/1.3/attribute/id.html
> Modifica article citations

- packtools/sps/validation/aff.py
- packtools/sps/validation/article_xref.py
- tests/sps/models/test_article_and_subarticles.py
- tests/sps/validation/test_aff.py
- tests/sps/validation/test_article_and_subarticles.py
- tests/sps/validation/test_article_xref.py
Corrige problemas remanescentes dos procedimentos de validação para: `xref`, afiliações e idiomas.
Por _commit_.
Avaliando os testes:
```
python3 -m unittest -v tests/sps/models/test_article_and_subarticles.py
python3 -m unittest -v tests/sps/validation/test_article_and_subarticles.py
python3 -m unittest -v tests/sps/validation/test_aff.py
python3 -m unittest -v tests/sps/validation/test_article_xref.py
```
NA.
NA.
NA.
NA.
> Validade general improvements

- packtools/sps/models/article_and_subarticles.py
- packtools/sps/validation/article_and_subarticles.py
- packtools/sps/validation/exceptions.py
- packtools/validation_report_generator.py
- tests/sps/models/test_article_and_subarticles.py
- tests/sps/validation/test_article_and_subarticles.py
Adiciona validações para elementos de `<article>` e `<sub-article>`
Por _commit_.
Avaliando os testes:
`python3 -m unittest -v tests/sps/models/test_article_and_subarticles.py`
NA.
NA.
NA.
NA.
> Validate article

- packtools/sps/validation/article_and_subarticles.py
- packtools/sps/validation/article_doi.py
- tests/sps/validation/test_article_and_subarticles.py
- tests/sps/validation/test_article_doi.py
Adiciona classes de validação para DOI.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_doi.py`
NA.
NA.
NA.
NA.
> Doi validation

- packtools/sps/validation/dates.py
- packtools/sps/validation/exceptions.py
- tests/sps/validation/test_dates.py
Adiciona funções de validação para data de publicação de artigo.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_dates.py`
NA.
NA.
NA.
NA.
> Date validation

- packtools/sps/validation/article_authors.py
- tests/sps/validation/test_article_authors.py
Refatora validação de papéis dos contribuidores de acordo com a taxonomia CRediT.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_authors.py`
NA.
NA.
NA.
n/a
> Validate roles

- packtools/sps/validation/exceptions.py
- packtools/sps/validation/related_articles.py
- tests/sps/validation/test_related_articles.py
Adiciona funções para a validação de artigos relacionados.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_related_articles.py`
NA.
NA.
NA.
NA.
> Related article validation

- packtools/sps/validation/article_authors.py
- tests/sps/validation/test_article_authors.py
Modifica o retorno da função de validação do ORCID
Por _commit_
`python3 -m unittest -v tests/sps/validation/test_article_authors.py`
NA.
NA.
NA.
NA.
> Article orcid validation

- packtools/catalogs/htmlgenerator/v2.0/article-text-xref.xsl
Modifica a apresentação de `xref[@ref-type="bibr"]` condicionado a `ref-list/ref/label` que significa que são referências numeradas
https://www.scielo.br/j/ocr/a/JmwhLpWvrmHTdCtJsmHh6CM/?lang=en
Buscar:
```
( Clements et al., 2022, 2023)
```
> Modifica a apresentação de `xref[@ref-type="bibr"]`

- packtools/sps/validation/preprint.py
- tests/sps/validation/test_preprint.py
Adiciona procedimento de validação para 'preprint'.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_preprint.py`
NA.
NA.
NA.
NA.
> Preprint validation

- packtools/sps/models/article_license.py
- packtools/sps/validation/article_license.py
- packtools/sps/validation/exceptions.py
- tests/sps/validation/test_article_license.py
Padroniza os procedimentos de validação para `article license`.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_license.py`
NA.
NA.
TK #516 
NA.
> Article license validate

- requirements.txt
Atualiza as Dependências do arquivo requirements.txt
pelo commit https://github.com/scieloorg/packtools/commit/12a35f017ee701c00c985e8dae939da5f6373079
Executando o seguinte comando 
```console.log
python3 setup.py test
```
N/A
N/A
N/A
N/A
> Atualiza Dependências

- packtools/sps/pid_provider/xml_sps_adapter.py
- packtools/sps/pid_provider/xml_sps_lib.py
- tests/sps/pid_provider/test_xmlsps.py
Adiciona XMLWithPre.article_publication_date.setter e PidProviderXMLAdapter.z_journal_title, funcionalidade para uso do pid provider.
Por commits
n/a
n/a
n/a
n/a
n/a
> Adiciona XMLWithPre.article_publication_date.setter e PidProviderXMLAdapter.z_journal_title

- packtools/sps/pid_provider/xml_sps_lib.py
Adiciona o parâmetro pretty_print em finger_print e get_zip_content em métodos de XMLWithPre
> Adiciona o parâmetro pretty_print em finger_print e get_zip_content em métodos de XMLWithPre

- packtools/sps/models/base_text_node.py
- packtools/sps/models/kwd_group.py
- tests/sps/models/test_kwd_group.py
> Refatora keywords

- packtools/sps/pid_provider/xml_sps_lib.py
- packtools/utils.py
Adiciona atributos em XMLWithPre: zip_file_path, xml_file_path, uri, update_xml_in_zip_file.
Também adiciona o parâmetro para realizar a compressão.
Por commits
Instanciando XMLWithPre usando create e path igual a um arquivo zip.
Altere algum dado de xml_with_pre e atualize o zip.
```python
for i in XMLWithPre.create(path='/tmp/package.zip'):
i.v2 = '12345678901234567890123'
i.update_xml_in_zip_file()
```
n/a
n/a
n/a
n/a
> Feat: Adiciona atributos em XMLWithPre

- packtools/sps/pid_provider/xml_sps_lib.py
- packtools/sps/validation/xml_structure.py
Adiciona validação de estrutura do XML (doctype, dtd, style)
Por commits
```python
from packtools.sps.pid_provider.xml_sps_lib import XMLWithPre
from packtools.sps.validation.xml_structure import StructureValidator
for i in XMLWithPre.create(path='/Users/roberta.takenaka/0103-7331-physis-33-05.zip'):
sv = StructureValidator(i)
print(sv.validate())
```
n/a
n/a
n/a
n/a
> Adiciona validação de estrutura do XML (doctype, dtd, style)

- packtools/sps/validation/related_articles.py
- packtools/sps/validation/utils.py
- tests/sps/validation/test_related_articles.py
Refatora validação de artigos relacionados.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_related_articles.py`
Este PR substitui o PR #598.
NA.
NA.
NA.
> Feat: related article new

- packtools/sps/validation/front_articlemeta_issue.py
- tests/sps/validation/test_front_articlemeta_issue.py
Adiciona as melhorias solicitadas para a validação de paginação.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_front_articlemeta_issue.py`
Este PR implementa as solicitações de melhorias apontadas no PR #603.
NA.
NA.
NA.
> Feat: pagination validation new

- packtools/sps/models/article_citations.py
- packtools/sps/validation/article_citations.py
- tests/sps/models/test_article_citations.py
- tests/sps/validation/test_article_citations.py
Refatora a classe de validação de citações
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_citations.py`
Este PR substitui o PR #600
NA.
NA.
NA.
> Refactor: citation authors new

- packtools/sps/models/article_author_notes.py
- packtools/sps/validation/article_author_notes.py
- packtools/sps/validation/exceptions.py
- tests/sps/models/test_article_author_notes.py
- tests/sps/validation/test_article_author_notes.py
Adiciona classe de validação para `author-notes`.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_author_notes.py`
NA.
NA.
NA.
NA.
> Feat: article author notes validation

- packtools/sps/models/article_contribs.py
Adiciona verificação dos parâmetros da função: `_get_affs(affs, contrib)` e corrige formatação geral:
NA.
NA.
NA.
NA.
NA.
NA.
> Fix: adiciona verificação de parâmetros na função '_get_affs' e corrige formatação geral

- packtools/sps/models/fig.py
- packtools/sps/models/tablewrap.py
Cria os modelos para lidar com figuras e tabelas dos XML
por commits
.
.
.
.
.
> Cria os modelos para lidar com figuras e tabelas dos XML

- packtools/sps/pid_provider/xml_sps_lib.py
Adiciona função de gerar um zip para cada artigo de um zip com vários artigos e faz correção da função get_xml_items_from_zip_file
por commits
[problemaleitura.zip](https://github.com/scieloorg/packtools/files/15409829/problemaleitura.zip)
```python
from packtools.sps.pid_provider.xml_sps_lib import get_xml_items_from_zip_file, get_zips
for item in get_xml_items_from_zip_file('/Users/roberta.takenaka/Downloads/problemaleitura.zip'):
print(item)
for item in get_zips('/Users/roberta.takenaka/Downloads/problemaleitura.zip'):
with open(item['zipfilename'], 'wb') as fp:
fp.write(item['content'])
print(item['zipfilename'])
0103-7331-physis-33-e33021.zip
._0103-7331-physis-33-e33021.zip
```
n/a
n/a
n/a
n/a
> Adiciona função de gerar um zip para cada artigo de um zip com vários artigos e faz correção da função get_xml_items_from_zip_file

- packtools/sps/pid_provider/xml_sps_lib.py
Adiciona atributos de uso recorrente em XMLWithPre: components, renditions, filenames, main_lang, langs
por commits
```python
from packtools.sps.pid_provider.xml_sps_lib import XMLWithPre
for item in XMLWithPre.create(path='/Users/roberta.takenaka/2448-2455-jpe-34-0223.zip'):
print(item.files)
for k, v in item.components.items():
print(k)
print(v)
```
n/a
n/a
n/a
n/a
> Adiciona a XMLWithPre: components, renditions, filenames, main_lang, langs

- packtools/catalogs/htmlgenerator/v2.0/article-text-back.xsl
- packtools/catalogs/htmlgenerator/v2.0/verse-group.xsl
Cria apresentação para verse-group e verse-line. Funciona para v2.0 e v3.0
Por commits
```console
python packtools/htmlgenerator.py --nonetwork --nochecks --loglevel DEBUG 1807-0299-alea-26-01-e62126.xml
```
n/a
https://github.com/scieloorg/opac/issues/3012
n/a
> Cria apresentação para verse-group e verse-line

- packtools/sps/pid_provider/xml_sps_lib.py
> Corrige XMLWithPre.assets

- packtools/sps/models/aff.py
- packtools/sps/models/app_group.py
- packtools/sps/models/article_citations.py
- packtools/sps/models/article_doi_with_lang.py
- packtools/sps/models/article_license.py
- packtools/sps/models/article_titles.py
- packtools/sps/validation/article_xref.py
- packtools/sps/validation/footnotes.py
- packtools/sps/validation/front_articlemeta_issue.py
- packtools/sps/validation/journal_meta.py
Padroniza as importações, utilizando o caminho completo, e remove importações não utilizadas.
NA
NA
NA
NA
TK #641 
NA
> Chore: standardizes imports

- packtools/sps/sps_versions/sps-1.9/contrib_type.json
- packtools/sps/sps_versions/sps-1.9/data_availability_specific_use.json
- packtools/sps/sps_versions/sps-1.9/date_type.json
- packtools/sps/sps_versions/sps-1.9/license_data.json
- packtools/sps/sps_versions/sps-1.9/meta_value.json
- packtools/sps/sps_versions/sps-1.9/publication_types_references.json
- packtools/sps/sps_versions/sps-1.9/related_article.json
- packtools/sps/sps_versions/sps-1.9/related_article__ext_link_type.json
- packtools/sps/sps_versions/sps-1.9/specific_use_for_peer_reviews.json
- packtools/sps/validation/peer_review.py
- tests/sps/validation/test_peer_review.py
Add json files into sps-1.9 and fix history dates import
> Add json files into sps-1.9 and fix history dates import

- packtools/sps/validation/funding_group.py
- tests/sps/validation/test_funding_group.py
Corrige a validação e adiciona teste.
Por _commit_
`python3 -m unittest -v tests/sps/validation/test_funding_group.py`
NA
NA
TK #665 
NA
> Fix: funding source validation

- packtools/sps/models/article_citations.py
- packtools/sps/validation/article_citations.py
- tests/sps/models/test_article_citations.py
- tests/sps/validation/test_article_citations.py
Adiciona validação para as `sub-tags` em `mixed-citation`.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_citations.py`
NA.
NA.
NA.
NA.
> Feat: mixed citation sub tags

- packtools/sps/models/article_dates.py
Adicionar "Season" em ArticleDates Processing
pelos commits
N/A
N/A
#730 
N/A
> [wip] Adicionar "Season" em ArticleDates Processing

- packtools/sps/models/article_contribs.py
Separa a extração de dados da tag <contrib-group> nas seções <article-meta> e <sub-article>
pelos commits
N/A
N/A
#739 
N/A
> Separa a extração de dados da tag <contrib-group> nas seções <article-meta> e <sub-article>

- packtools/sps/validation/article_citations.py
- packtools/sps/validation/utils.py
- packtools/sps/validation/xml_validations.py
- tests/sps/validation/test_article_citations.py
Corrige os parâmetros das classes e métodos das validações de referências.
Remove os parâmetros excedentes, adiciona os parâmetros faltantes.
Por commits
Executando:
```console
python -m unittest -v tests.sps.validation.test_article_citations
```
n/a
n/a
n/a
n/a
> Corrige os parâmetros das classes e métodos das validações de referências

- packtools/sps/models/formula.py
- packtools/sps/validation/formula.py
- packtools/sps/validation_rules/formula_rules.json
- tests/sps/models/test_formula.py
- tests/sps/validation/test_formula.py
Refatora a validação de fórmulas.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_formula.py`
NA.
NA.
NA.
NA.
> Refactor: formula validation

- packtools/sps/validation/xml_validations.py
> Corrige chamada de validação de figuras

- packtools/sps/validation/xml_validations.py
> Adiciona validação de tabelas (table-wrap)

- packtools/sps/validation/xml_validations.py
- packtools/sps/validation/xml_validator.py
- packtools/sps/validation_rules/formula_rules.json
> Adiciona validacao de equações (disp-formula e inline-formula)

- packtools/sps/models/article_and_subarticles.py
- tests/sps/models/test_article_and_subarticles.py
> Adiciona modelo Fulltext para lidar com os atributos e hierarquias de sub-articles

- tests/sps/validation/test_metadata_langs.py
Corrige a importação.
Por _commit_.
NA.
NA.
NA.
TK #802.
NA.
> Fix: metadata langs validation tests

- packtools/sps/models/v2/aff.py
- packtools/sps/validation/aff.py
- tests/sps/validation/test_aff.py
Corrige os testes automatizados de acordo com as modificações implementadas.
Por _commit_.
Sugiro avaliar os testes automatizados:
`python3 -m unittest -v tests/sps/validation/test_aff.py
`
NA.
NA.
TK #790 
NA.
> Fix: aff validation tests

- packtools/sps/models/front_articlemeta_issue.py
- packtools/sps/validation/exceptions.py
- packtools/sps/validation/front_articlemeta_issue.py
- packtools/sps/validation_rules/bibliographic_strip_rules.json
- packtools/sps/validation_rules/pagination_rules.json
- tests/sps/models/test_front_articlemeta_issue.py
- tests/sps/validation/test_front_articlemeta_issue.py
Refatora as validações e atualiza os testes para `front articlemeta`.
Por _commit_.
Sugiro avaliar os testes.
NA.
NA.
TK #800 
NA.
> Fix: Corrige validação dos dados relacionados com a legenda bibliográfica

- packtools/sps/validation/article_doi.py
- tests/sps/validation/test_article_doi.py
Adapta os testes de acordo com as melhorias implementadas.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_doi.py`
NA.
NA.
TK #797 
NA.
> Fix: article doi tests

- tests/sps/validation/test_article_author_notes.py
Adapta os testes de acordo com as melhorias implementadas.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_article_author_notes.py`
NA.
NA.
TK #793 
NA.
> Fix: author notes validation tests

- packtools/sps/validation/alternatives.py
- tests/sps/validation/test_alternatives.py
Corrige problemas com a validação de alternativas e atualiza os testes.
Por _commit_.
`python3 -m unittest -v tests/sps/validation/test_alternatives.py`
NA.
NA.
NA.
NA.
> Fix: alternatives validation tests

- packtools/sps/models/author_notes.py
- packtools/sps/validation_rules/author_notes_rules.json
- tests/sps/models/test_author_notes.py
Refatora modelos para `author_notes`.
NA.
NA.
NA.
NA.
NA.
NA.
> Refactor: author notes models

- packtools/sps/models/fn.py
- packtools/sps/validation_rules/fn_rules.json
- tests/sps/models/test_fn.py
Refatora modelos para `fn`.
NA.
NA.
NA.
NA.
NA.
NA.
> Refactor: fn models

- packtools/sps/models/basenotes.py
- tests/sps/models/test_basenotes.py
Refatora modelos para` basenotes`.
NA.
NA.
NA.
NA.
NA.
NA.
> Refactor: basenotes models

- packtools/sps/models/references.py
- packtools/sps/validation_rules/references_rules.json
- tests/sps/models/test_references.py
Refatora modelos para `references`.
NA.
NA.
NA.
NA.
NA.
NA.
> Refactor: references models

- packtools/sps/validation/fn.py
- tests/sps/validation/test_fn.py
Adiciona módulo com validações para `fn` e os respectivos testes.
NA.
NA.
NA.
NA.
NA.
NA.
> Refactor: fn validations

- packtools/sps/validation/references.py
- tests/sps/validation/test_references.py
Adiciona validação para `chapter_title` e `part_title` com os respectivos testes.
NA.
NA.
NA.
NA.
NA.
NA.
> Refactor: references validations

- packtools/sps/models/article_and_subarticles.py
- packtools/sps/validation/article_and_subarticles.py
- packtools/sps/validation_rules/article_and_subarticle_rules.json
- tests/sps/models/test_article_and_subarticles.py
Atualiza modelos para `article_and_subarticle`.
Por commit.
NA.
NA.
NA.
NA.
NA.
> Refactor: article and subarticles models

- packtools/sps/models/aff.py
- packtools/sps/models/article_license.py
- packtools/sps/models/article_titles.py
- packtools/sps/models/article_toc_sections.py
- packtools/sps/models/v2/article_toc_sections.py
- packtools/sps/utils/xml_utils.py
- tests/sps/models/test_article_titles.py
- tests/sps/models/test_xml_utils.py
- tests/sps/utils/test_xml_utils.py
Adiciona a obtenção de títulos que possuem o conteúdo de xref na sua composição.
Por _commit_.
Sugiro avaliar os testes.
NA.
NA.
TKs: #817 e #826 (parcialmente).
NA.
> Feat: title with xref contents

- packtools/sps/validation/utils.py
> Adiciona função para melhorar o 'advice' para os usuários

- requirements.txt
> Corrige requirements python-docx e python-docx

- packtools/sps/models/v2/article_toc_sections.py
Adiciona sec subsec em ArticleTocSections.sections para facilitar a validação
> Adiciona sec subsec em ArticleTocSections.sections para facilitar a validação

- packtools/sps/models/article_doi_with_lang.py
- packtools/sps/validation/article_doi.py
- packtools/sps/validation/utils.py
- packtools/sps/validation_rules/article_doi_rules.json
> Melhora advice validacao de doi

- packtools/sps/models/article_contribs.py
- packtools/sps/validation/article_contribs.py
- packtools/sps/validation_rules/article_contribs_rules.json
> Melhora advice de validacoes contribs

- packtools/sps/validation/article_data_availability.py
- packtools/sps/validation/utils.py
- packtools/sps/validation/xml_validations.py
- tests/sps/validation/test_article_data_availability.py
> Melhora advice de article data availability

- packtools/sps/validation/peer_review.py
- Adiciona resposta para validações de sucesso;
- Formata 'advice';
- Adiciona parâmetros: 'element_name', 'sub_element_name' e 'attribute_name'
Por _commit_.
NA.
NA.
NA.
TK #875 
NA.
> Melhorar o texto de 'advice' para validação de peer review

- packtools/sps/models/v2/article_toc_sections.py
- packtools/sps/validation/article_toc_sections.py
- packtools/sps/validation/xml_validations.py
- packtools/sps/validation_rules/article_toc_section_rules.json
- tests/sps/models/test_article_toc_sections.py
- tests/sps/validation/test_article_toc_sections.py
Melhora advice de validacoes de subject (seções do sumário)
por commits
```console
python -m unittest -v tests/sps/m*/test_article_toc*
```
```console
python -m unittest -v tests/sps/v*/test_article_toc*
```
n/a
n/a
n/a
n/a
> Melhora advice de validacoes de subject (seções do sumário)

- packtools/sps/models/dates.py
- packtools/sps/validation/dates.py
- tests/sps/validation/test_dates.py
> Melhora advice de validacao dates

- packtools/sps/validation/author_notes.py
- packtools/sps/validation/basefn.py
Ajusta o conteúdo de `advice` nas funções de validação de `fn`.
Por _commit_.
NA.
NA.
NA.
TK #878
NA.
> Fix: fn advice

- packtools/sps/validation/article_abstract.py
Ajusta o conteúdo de `advice` nas funções de validação de `article-abstract`.
Por _commit_.
NA.
NA.
NA.
TK #878 
NA.
> Fix: article abstract advice

- packtools/sps/validation/article_xref.py
Ajusta o conteúdo de `advice` nas funções de validação de `article-xref`.
Por _commit_.
NA.
NA.
NA.
TK #878 
NA.
> Fix: article xref advice

- packtools/sps/models/article_doi_with_lang.py
- packtools/sps/validation/article_doi.py
- tests/sps/models/test_article_doi_with_lang.py
- tests/sps/validation/test_article_doi.py
> Fix doi validation

- packtools/sps/models/article_contribs.py
- packtools/sps/validation/article_contribs.py
- tests/sps/validation/test_article_contribs.py
> Corrige defeitos do modelo e validação de contribs

- packtools/sps/models/dates.py
- packtools/sps/models/references.py
- packtools/sps/validation/article_and_subarticles.py
- packtools/sps/validation/article_data_availability.py
- packtools/sps/validation/dates.py
- packtools/sps/validation/front_articlemeta_issue.py
- packtools/sps/validation/references.py
- packtools/sps/validation/utils.py
- packtools/sps/validation/xml_validations.py
> Corrige bugs em modelos e validacoes

- packtools/sps/validation/article_contribs.py
> Corrige bugs em validacao de contribs

- packtools/sps/validation/article_license.py
Ajusta o conteúdo de `advice` nas funções de validação de `article-license`.
Por _commit_.
NA.
NA.
NA.
TK #878 
NA.
> Fix: article license advice

- packtools/sps/validation/aff.py
Corrige as mensagesn em `advice` para as validações de `aff.`
Por _commit_.
NA.
NA.
NA.
TK #895 
NA.
> Fix: message in 'advice' for 'aff'

- packtools/sps/validation/funding_group.py
Ajusta o conteúdo de `advice` nas funções de validação de `funding-group`.
Por _commit_.
NA.
NA.
NA.
TK #878 
NA.
> Fix: funding group advice

- packtools/sps/validation/fig.py
- packtools/sps/validation/formula.py
- packtools/sps/validation/tablewrap.py
Ajusta o conteúdo de `advice` nas funções de validação de `<fig>`, `<formula>` e `<table-wrap>`.
Por _commit_.
NA.
NA.
NA.
TK #878 
NA.
> Fix: figs, formulas and tables advice

- packtools/sps/validation/aff.py
- packtools/sps/validation_rules/aff_rules.json
- tests/sps/validation/test_aff.py
> Revisao validacoes wip 3 aff

- packtools/sps/models/funding_group.py
- packtools/sps/validation/funding_group.py
- packtools/sps/validation_rules/funding_data_rules.json
> Revisao validacoes wip 3 funding group

- packtools/data_checker.py
- packtools/sps/validation/xml_validations.py
- packtools/sps/validation/xml_validator.py
- packtools/sps/validation/xml_validator_rules.py
Melhora data_checker e corrige o modo de leitura do json que são parâmetros de validação
> Melhora data_checker e corrige o modo de leitura do json que são parâmetros de validação

- packtools/sps/validation/xml_validator.py
> Corrige nome do módulo na importação

- packtools/sps/models/v2/article_xref.py
- packtools/sps/validation/article_xref.py
- packtools/sps/validation_rules/id_and_rid_match_rules.json
- tests/sps/validation/test_article_xref.py
> Revisa validações de xref

- packtools/sps/models/fn.py
- packtools/sps/validation/fn.py
- packtools/sps/validation/xml_validator.py
> Corrige validate_edited_by

- packtools/sps/validation/fn.py
> Corrige validação de fn_edited_by

- packtools/sps/validation/fn.py
- packtools/sps/validation/xml_validations.py
> Corrige validacao fn edited by2

- packtools/sps/models/v2/article_toc_sections.py
- packtools/sps/validation/article_and_subarticles.py
- packtools/sps/validation/article_contribs.py
- tests/sps/validation/test_article_and_subarticles.py
- tests/sps/validation/test_article_contribs.py
> Corrige validação de correspondência entre article-type e o título de seção do artigo (en) e corrige validação de CREDIT

- packtools/sps/models/v2/abstract.py
- packtools/sps/validation/article_abstract.py
- packtools/sps/validation/xml_validations.py
- packtools/sps/validation_rules/abstract_rules.json
> Wip 5a abstract

- packtools/catalogs/htmlgenerator/v2.0/article-meta-contrib.xsl
- tests/fixtures/htmlgenerator/contrib-group-duplo/2237-9622-ress-33-spe2-e20231216.en.3_0.html
- tests/fixtures/htmlgenerator/contrib-group-duplo/2237-9622-ress-33-spe2-e20231216.en.html
- tests/fixtures/htmlgenerator/contrib-group-duplo/2237-9622-ress-33-spe2-e20231216.pt.3_0.html
- tests/fixtures/htmlgenerator/contrib-group-duplo/2237-9622-ress-33-spe2-e20231216.pt.html
- tests/fixtures/htmlgenerator/contrib-group-duplo/2237-9622-ress-33-spe2-e20231216.xml
Corrige a apresentação do botão 'autoria' (apenas 1 vez)
por commits
```console
python packtools/htmlgenerator.py tests/fixtures/htmlgenerator/contrib-group-duplo/2237-9622-ress-33-spe2-e20231216.xml --nonetwork --nochecks
```
n/a
n/a
https://github.com/scieloorg/opac_5/issues/193
n/a
> Corrige a apresentação do botão 'autoria' (apenas 1 vez)

- packtools/catalogs/htmlgenerator/v3.0/article-meta-abstract.xsl
- tests/fixtures/htmlgenerator/abstracts/FngWzPqXpsVJGyxLD5PSHPg.en.3_0.html
- tests/fixtures/htmlgenerator/abstracts/FngWzPqXpsVJGyxLD5PSHPg.en.html
- tests/fixtures/htmlgenerator/abstracts/FngWzPqXpsVJGyxLD5PSHPg.pt.3_0.html
- tests/fixtures/htmlgenerator/abstracts/FngWzPqXpsVJGyxLD5PSHPg.pt.html
- tests/fixtures/htmlgenerator/abstracts/summary.en.3_0.html
- tests/fixtures/htmlgenerator/abstracts/summary.en.html
- tests/fixtures/htmlgenerator/abstracts/summary.xml
https://github.com/scieloorg/opac_5/issues/231
https://github.com/scieloorg/opac_5/issues/232
> Apresenta os resumos em uma nova ordem e apresenta summary

- packtools/sps/models/article_dates.py
- tests/sps/models/test_article_dates.py
Corrige a classificação de datas para definir datas completas (dia, mês e ano) como "pub" e incompletas como "collection".
NA
NA
NA
NA
NA
NA
> Corrige a classificação de datas

- tests/sps/models/test_dates.py
Os testes foram atualizados para alinhar as chaves e propriedades com a nova estrutura, garantindo a validação correta da extração e formatação das datas.
NA
NA
NA
NA
NA
NA
> Adapta os testes às correções implementadas para o modelo de dates

- packtools/sps/pid_provider/xml_sps_lib.py
> Cria funções alternativas para obter os xmls do zip

- packtools/sps/models/label_and_caption.py
Adiciona modelo `LabelAndCaption`.
Pro _commit_.
NA
NA
NA
Substitui PR #915 
NA
> Adiciona modelo LabelAndCaption

- packtools/sps/models/graphic.py
- tests/sps/models/test_graphic.py
Adiciona modelo `Graphic` e testes.
NA
NA
NA
NA
NA
> Adiciona modelo Graphic e testes

- packtools/sps/models/media.py
- tests/sps/models/test_media.py
Corrige modelo `Media` e testes.
NA
NA
NA
NA
NA
> Corrige modelo Media e testes

- packtools/sps/models/app_group.py
- tests/sps/models/test_app_group.py
Corrige modelo `App` e testes.
NA
NA
NA
NA
NA
> Corrige modelo App e testes

- packtools/sps/pid_provider/xml_sps_lib.py
> Adiciona parâmetros caputre_errors e timeout a XMLWithPre.create

- packtools/catalogs/htmlgenerator/v3.0/article-meta-abstract.xsl
Corrige a apresentação da página do resumo representado pela tag trans-abstract
Indique as referências utilizadas para a elaboração do …
> Corrige a apresentação das palavras chaves presentes em sub-article

- packtools/sps/validation/visual_resource_base.py
- packtools/sps/validation_rules/visual_resource_base_rules.json
Adiciona validação para `VisualResourceBase`.
NA
NA
NA
NA
Susbtitui o PR #915 
NA
> Adiciona validação para VisualResourceBase

- packtools/sps/validation/media.py
- tests/sps/validation/test_media.py
Corrige validação para `Media` e testes.
NA
NA
NA
NA
NA
> Corrige validação para Media e testes

- packtools/sps/validation/graphic.py
Adiciona validação para `Graphic`.
NA
NA
NA
NA
NA
> Adiciona validação para Graphic

- packtools/sps/models/article_contribs.py
- tests/sps/models/test_article_contribs.py
- tests/sps/models/test_dates.py
Os testes foram atualizados para alinhamento com as modificações feitas para o modelo de `contribs`.
NA.
NA.
NA.
NA.
NA.
NA.
> Fix: article contribs tests

- tests/sps/models/test_front_articlemeta_issue.py
Complementa o dicionário para `front_articlemeta_issue`.
NA
NA
NA
NA
NA
NA
> Corrige os testes para 'front_articlemeta_issue'

- tests/sps/models/test_funding_group.py
Corrige os dicionários de respostas para adequação às modificações no modelo.
NA
NA
NA
NA
NA
NA
> Corrige os testes para 'funding_group'

- tests/sps/models/test_graphic.py
Corrige a quantidade de elementos identificados no teste para `graphic`.
NA
NA
NA
NA
NA
NA
> Corrige os testes para graphic

- packtools/sps/validation/accessibility_data.py
- packtools/sps/validation_rules/accessibility_data_rules.json
- tests/sps/validation/test_accessibility_data.py
Adiciona validação para AccessibilityData e testes.
NA
NA
NA
NA
NA
> Adiciona validação para AccessibilityData e testes

- packtools/sps/models/accessibility_data.py
- packtools/sps/models/app_group.py
- packtools/sps/models/media.py
- packtools/sps/models/visual_resource_base.py
- packtools/sps/pid_provider/xml_sps_lib.py
- packtools/sps/validation/accessibility_data.py
- packtools/sps/validation/app_group.py
- packtools/sps/validation/media.py
- packtools/sps/validation/visual_resource_base.py
- packtools/sps/validation/xml_validations.py
- packtools/sps/validation/xml_validator.py
- packtools/sps/validation_rules/accessibility_data_rules.json
- packtools/sps/validation_rules/visual_resource_base_rules.json
Corrige os modelos e validações referentes à acessibilidade, media, app, material suplementar (ainda que incompleto)
por commits
Considere ter vários xmls na pasta **xmls** e informe uma pasta para a saída, por exemplo, **output** 
Execute o seguinte comando:
```console
python packtools/data_checker.py xmls output
```
Verifique o conteúdo de **output**
Será necessário revisar os testes
n/a
n/a
n/a
> Corrige os modelos e validações referentes à acessibilidade, media, app, material suplementar (ainda que incompleto)

- packtools/sps/models/accessibility_data.py
- packtools/sps/validation/accessibility_data.py
- tests/sps/models/test_accessibility_data.py
- tests/sps/validation/test_accessibility_data.py
Padroniza o conteúdo de advice para as validações. Considerando a seguinte regra de formação:
1. O que está errado
2. Onde está errado
3. Como corrigir
NA
NA
NA
NA
NA
NA
> Fix: advice and tests accessibility data

- packtools/sps/models/visual_resource_base.py
- tests/sps/models/test_visual_resource_base.py
- tests/sps/validation/test_visual_resource_base.py
Corrige os testes para `VisualResourceBase`.
NA
NA
NA
NA
NA
NA
> Fix: visual resource tests

- packtools/sps/validation/app_group.py
- packtools/sps/validation_rules/app_group_rules.json
- tests/sps/validation/test_app_group.py
Adiciona `app_group_rules.json`, refatora validação e adapta os testes.
NA
NA
NA
NA
NA
NA
> Fix: app group rules

- packtools/sps/validation/visual_resource_base.py
- packtools/sps/validation/xml_validations.py
- packtools/sps/validation_rules/supplementary_material_rules.json
Complementa rules e corrige validação de `@id` para tratar casos sem tag ou XML definido.
NA
NA
NA
NA
NA
NA
> Fix: supplementary material rules

- packtools/sps/validation_rules/visual_resource_base_rules.json
Complementa `visual_resource_base_rules`.
NA
NA
NA
NA
NA
NA
> Fix: visual resource base rules

- packtools/sps/formats/crossref.py
- tests/sps/formats/test_crossref.py
- tests/sps/models/test_article_contribs.py
Corrige gerador de formato `crossref` para adequação às melhorias dos modelos.
NA
NA
NA
NA
NA
NA
> Fix: crossref format

- packtools/sps/formats/pubmed.py
Corrige o formato PubMed
NA
NA
NA
NA
NA
NA
> Fix: pubmed format

- packtools/sps/formats/crossref.py
- packtools/sps/libs/requester.py
- packtools/sps/models/aff.py
- packtools/sps/models/app_group.py
- packtools/sps/models/article_titles.py
- packtools/sps/models/dates.py
- packtools/sps/models/media.py
- packtools/sps/models/references.py
- packtools/sps/models/tablewrap.py
- packtools/sps/models/v2/abstract.py
- packtools/sps/pid_provider/xml_sps_adapter.py
- packtools/sps/pid_provider/xml_sps_lib.py
- packtools/sps/validation/aff.py
- packtools/sps/validation/article_and_subarticles.py
- packtools/sps/validation/article_data_availability.py
- packtools/sps/validation/article_toc_sections.py
- packtools/sps/validation/dates.py
- packtools/sps/validation/front_articlemeta_issue.py
- packtools/sps/validation/graphic.py
- packtools/sps/validation/peer_review.py
- packtools/sps/validation/references.py
- packtools/sps/validation/tablewrap.py
- packtools/sps/validation/utils.py
- packtools/sps/validation/xml_validator_rules.py
Remove importações não utilizadas.
NA
NA
NA
NA
TK #965 
NA
> Remove importações não utilizadas

- packtools/sps/utils/xml_utils.py
> Cria remove_comments() e usa-a em node_text()

- packtools/sps/pid_provider/models/article_and_subarticles.py
- packtools/sps/pid_provider/models/article_assets.py
- packtools/sps/pid_provider/models/article_authors.py
- packtools/sps/pid_provider/models/article_dates.py
- packtools/sps/pid_provider/models/article_doi_with_lang.py
- packtools/sps/pid_provider/models/article_ids.py
- packtools/sps/pid_provider/models/article_renditions.py
- packtools/sps/pid_provider/models/article_titles.py
- packtools/sps/pid_provider/models/body.py
- packtools/sps/pid_provider/models/dates.py
- packtools/sps/pid_provider/models/front_articlemeta_issue.py
- packtools/sps/pid_provider/models/journal_meta.py
- packtools/sps/pid_provider/models/related_articles.py
- packtools/sps/pid_provider/xml_sps_lib.py
Isola os modelos utilizados por `pid_provider` considerando v4.7.1.
NA.
NA.
NA.
NA.
NA.
NA.
> Packtools pid provider 4.7.1

- packtools/sps/formats/am/am.py
Atualiza importação
NA.
NA.
NA.
NA.
NA.
NA.
> Corrige importação de ArticleDates

- packtools/sps/formats/am/am.py
- packtools/sps/models/references.py
- tests/sps/formats/am/test_am.py
Valida gerador de formato AM.
NA.
NA.
NA.
NA.
TK #997 
NA.
> Corrige formato AM para as referências (autores, páginas, edition, ...)

- packtools/catalogs/htmlgenerator/v3.0/article-text-supplementary-material.xsl
https://github.com/scieloorg/opac_5/issues/313
> Corrige a apresentação da seção de material suplementar para conseguir descarregar o arquivo

- packtools/catalogs/htmlgenerator/v3.0/article-text-xref.xsl
> Corrige defeito de uso de starts-with (xref bibr)

- packtools/catalogs/htmlgenerator/v3.0/html-modals-contribs.xsl
> Remove o número 2 que foi inserido sem intenção

- packtools/sps/pid_provider/xml_sps_lib.py
> Voltar a ser lista para não haver problema com serialização

- packtools/catalogs/htmlgenerator/v3.0/html-modals-contribs.xsl
> Corrige o link do orcid

- packtools/sps/formats/orcid/payload_builder.py
- tests/sps/formats/orcid/test_payload_builder.py
> Reorganiza o módulo que gera o payload para o registro do trabalho no ORCID

- packtools/sps/pid_provider/xml_sps_lib.py
> aprimora tratamento de erro de leitura de xml incluso em zip
